// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FlatBuffers.RtpParameters
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum MediaKind : byte
    {
        [EnumMember(Value = nameof(audio))]
        audio = 0,

        [EnumMember(Value = nameof(video))]
        video = 1,
    }
}
