// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffers.RtpParameters
{
    public enum Value : byte
    {
        NONE = 0,

        Boolean = 1,

        Integer32 = 2,

        Double = 3,

        String = 4,

        Integer32Array = 5,
    }

    public class ValueUnion
    {
        public Value Type { get; set; }
        public object Value_ { get; set; }

        public ValueUnion()
        {
            this.Type = Value.NONE;
            this.Value_ = null;
        }

        public T As<T>() where T : class { return this.Value_ as T; }
        public BooleanT AsBoolean() { return this.As<BooleanT>(); }
        public static ValueUnion FromBoolean(BooleanT _boolean) { return new ValueUnion { Type = Value.Boolean, Value_ = _boolean }; }
        public Integer32T AsInteger32() { return this.As<Integer32T>(); }
        public static ValueUnion FromInteger32(Integer32T _integer32) { return new ValueUnion { Type = Value.Integer32, Value_ = _integer32 }; }
        public DoubleT AsDouble() { return this.As<DoubleT>(); }
        public static ValueUnion FromDouble(DoubleT _double) { return new ValueUnion { Type = Value.Double, Value_ = _double }; }
        public StringT AsString() { return this.As<StringT>(); }
        public static ValueUnion FromString(StringT _string) { return new ValueUnion { Type = Value.String, Value_ = _string }; }
        public Integer32ArrayT AsInteger32Array() { return this.As<Integer32ArrayT>(); }
        public static ValueUnion FromInteger32Array(Integer32ArrayT _integer32array) { return new ValueUnion { Type = Value.Integer32Array, Value_ = _integer32array }; }

        public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, ValueUnion _o)
        {
            switch(_o.Type)
            {
                default:
                    return 0;
                case Value.Boolean:
                    return Boolean.Pack(builder, _o.AsBoolean()).Value;
                case Value.Integer32:
                    return Integer32.Pack(builder, _o.AsInteger32()).Value;
                case Value.Double:
                    return Double.Pack(builder, _o.AsDouble()).Value;
                case Value.String:
                    return String.Pack(builder, _o.AsString()).Value;
                case Value.Integer32Array:
                    return Integer32Array.Pack(builder, _o.AsInteger32Array()).Value;
            }
        }
    }
}
