// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using System.Collections.Generic;
using Google.FlatBuffers;
using MediasoupSharp.FlatBuffers.RtpStream.T;

namespace FlatBuffers.RtpStream
{
    public struct RecvStats : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static RecvStats GetRootAsRecvStats(ByteBuffer _bb) { return GetRootAsRecvStats(_bb, new RecvStats()); }
        public static RecvStats GetRootAsRecvStats(ByteBuffer _bb, RecvStats obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public RecvStats __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public Stats? Base { get { int o = __p.__offset(4); return o != 0 ? (Stats?)(new Stats()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public uint Jitter { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public ulong PacketCount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
        public ulong ByteCount { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
        public uint Bitrate { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public BitrateByLayer? BitrateByLayer(int j) { int o = __p.__offset(14); return o != 0 ? (BitrateByLayer?)(new BitrateByLayer()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int BitrateByLayerLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static Offset<RecvStats> CreateRecvStats(FlatBufferBuilder builder,
                                                        Offset<Stats> @baseOffset = default(Offset<Stats>),
                                                        uint jitter = 0,
                                                        ulong packet_count = 0,
                                                        ulong byte_count = 0,
                                                        uint bitrate = 0,
                                                        VectorOffset bitrate_by_layerOffset = default(VectorOffset))
        {
            builder.StartTable(6);
            RecvStats.AddByteCount(builder, byte_count);
            RecvStats.AddPacketCount(builder, packet_count);
            RecvStats.AddBitrateByLayer(builder, bitrate_by_layerOffset);
            RecvStats.AddBitrate(builder, bitrate);
            RecvStats.AddJitter(builder, jitter);
            RecvStats.AddBase(builder, @baseOffset);
            return RecvStats.EndRecvStats(builder);
        }

        public static void StartRecvStats(FlatBufferBuilder builder) { builder.StartTable(6); }
        public static void AddBase(FlatBufferBuilder builder, Offset<Stats> baseOffset) { builder.AddOffset(0, baseOffset.Value, 0); }
        public static void AddJitter(FlatBufferBuilder builder, uint jitter) { builder.AddUint(1, jitter, 0); }
        public static void AddPacketCount(FlatBufferBuilder builder, ulong packetCount) { builder.AddUlong(2, packetCount, 0); }
        public static void AddByteCount(FlatBufferBuilder builder, ulong byteCount) { builder.AddUlong(3, byteCount, 0); }
        public static void AddBitrate(FlatBufferBuilder builder, uint bitrate) { builder.AddUint(4, bitrate, 0); }
        public static void AddBitrateByLayer(FlatBufferBuilder builder, VectorOffset bitrateByLayerOffset) { builder.AddOffset(5, bitrateByLayerOffset.Value, 0); }
        public static VectorOffset CreateBitrateByLayerVector(FlatBufferBuilder builder, Offset<BitrateByLayer>[] data) { builder.StartVector(4, data.Length, 4); for(int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateBitrateByLayerVectorBlock(FlatBufferBuilder builder, Offset<BitrateByLayer>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateBitrateByLayerVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<BitrateByLayer>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateBitrateByLayerVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<BitrateByLayer>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartBitrateByLayerVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<RecvStats> EndRecvStats(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // base
            builder.Required(o, 14);  // bitrate_by_layer
            return new Offset<RecvStats>(o);
        }
        public RecvStatsT UnPack()
        {
            var _o = new RecvStatsT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(RecvStatsT _o)
        {
            _o.Base = this.Base.HasValue ? this.Base.Value.UnPack() : null;
            _o.Jitter = this.Jitter;
            _o.PacketCount = this.PacketCount;
            _o.ByteCount = this.ByteCount;
            _o.Bitrate = this.Bitrate;
            _o.BitrateByLayer = new List<BitrateByLayerT>();
            for(var _j = 0; _j < this.BitrateByLayerLength; ++_j)
            { _o.BitrateByLayer.Add(this.BitrateByLayer(_j).HasValue ? this.BitrateByLayer(_j).Value.UnPack() : null); }
        }
        public static Offset<RecvStats> Pack(FlatBufferBuilder builder, RecvStatsT _o)
        {
            if(_o == null)
                return default(Offset<RecvStats>);
            var _base = _o.Base == null ? default(Offset<Stats>) : Stats.Pack(builder, _o.Base);
            var _bitrate_by_layer = default(VectorOffset);
            if(_o.BitrateByLayer != null)
            {
                var __bitrate_by_layer = new Offset<BitrateByLayer>[_o.BitrateByLayer.Count];
                for(var _j = 0; _j < __bitrate_by_layer.Length; ++_j)
                { __bitrate_by_layer[_j] = RtpStream.BitrateByLayer.Pack(builder, _o.BitrateByLayer[_j]); }
                _bitrate_by_layer = CreateBitrateByLayerVector(builder, __bitrate_by_layer);
            }
            return CreateRecvStats(
              builder,
              _base,
              _o.Jitter,
              _o.PacketCount,
              _o.ByteCount,
              _o.Bitrate,
              _bitrate_by_layer);
        }
    }
}
