// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using FlatBuffers.Consumer;
using FlatBuffers.DataConsumer;
using FlatBuffers.PlainTransport;
using FlatBuffers.Router;
using FlatBuffers.RtpObserver;
using FlatBuffers.Transport;
using FlatBuffers.Worker;
using MediasoupSharp.FlatBuffers.Consumer.T;
using MediasoupSharp.FlatBuffers.DataConsumer.T;
using MediasoupSharp.FlatBuffers.PlainTransport.T;
using MediasoupSharp.FlatBuffers.RtpObserver.T;
using MediasoupSharp.FlatBuffers.Transport.T;
using MediasoupSharp.FlatBuffers.Worker.T;
using EnableTraceEventRequest = FlatBuffers.Transport.EnableTraceEventRequest;
using EnableTraceEventRequestT = MediasoupSharp.FlatBuffers.Producer.T.EnableTraceEventRequestT;

namespace FlatBuffers.Request
{
    public enum Body : byte
    {
        NONE                                              = 0,
        Worker_UpdateSettingsRequest                      = 1,
        Worker_CreateWebRtcServerRequest                  = 2,
        Worker_CloseWebRtcServerRequest                   = 3,
        Worker_CreateRouterRequest                        = 4,
        Worker_CloseRouterRequest                         = 5,
        Router_CreateWebRtcTransportRequest               = 6,
        Router_CreatePlainTransportRequest                = 7,
        Router_CreatePipeTransportRequest                 = 8,
        Router_CreateDirectTransportRequest               = 9,
        Router_CreateActiveSpeakerObserverRequest         = 10,
        Router_CreateAudioLevelObserverRequest            = 11,
        Router_CloseTransportRequest                      = 12,
        Router_CloseRtpObserverRequest                    = 13,
        Transport_SetMaxIncomingBitrateRequest            = 14,
        Transport_SetMaxOutgoingBitrateRequest            = 15,
        Transport_SetMinOutgoingBitrateRequest            = 16,
        Transport_ProduceRequest                          = 17,
        Transport_ConsumeRequest                          = 18,
        Transport_ProduceDataRequest                      = 19,
        Transport_ConsumeDataRequest                      = 20,
        Transport_EnableTraceEventRequest                 = 21,
        Transport_CloseProducerRequest                    = 22,
        Transport_CloseConsumerRequest                    = 23,
        Transport_CloseDataProducerRequest                = 24,
        Transport_CloseDataConsumerRequest                = 25,
        PlainTransport_ConnectRequest                     = 26,
        PipeTransport_ConnectRequest                      = 27,
        WebRtcTransport_ConnectRequest                    = 28,
        Producer_EnableTraceEventRequest                  = 29,
        Consumer_SetPreferredLayersRequest                = 30,
        Consumer_SetPriorityRequest                       = 31,
        Consumer_EnableTraceEventRequest                  = 32,
        DataConsumer_SetBufferedAmountLowThresholdRequest = 33,
        DataConsumer_SendRequest                          = 34,
        DataConsumer_SetSubchannelsRequest                = 35,
        DataConsumer_AddSubchannelRequest                 = 36,
        DataConsumer_RemoveSubchannelRequest              = 37,
        RtpObserver_AddProducerRequest                    = 38,
        RtpObserver_RemoveProducerRequest                 = 39,
    };

    public class BodyUnion
    {
        public Body Type { get; set; }
        public object Value { get; set; }

        public BodyUnion()
        {
            this.Type = Body.NONE;
            this.Value = null;
        }

        public T As<T>() where T : class { return this.Value as T; }
        public UpdateSettingsRequestT AsWorker_UpdateSettingsRequest() { return this.As<UpdateSettingsRequestT>(); }
        public static BodyUnion FromWorker_UpdateSettingsRequest(UpdateSettingsRequestT _worker_updatesettingsrequest) { return new BodyUnion { Type = Body.Worker_UpdateSettingsRequest, Value = _worker_updatesettingsrequest }; }
        public CreateWebRtcServerRequestT AsWorker_CreateWebRtcServerRequest() { return this.As<CreateWebRtcServerRequestT>(); }
        public static BodyUnion FromWorker_CreateWebRtcServerRequest(CreateWebRtcServerRequestT _worker_createwebrtcserverrequest) { return new BodyUnion { Type = Body.Worker_CreateWebRtcServerRequest, Value = _worker_createwebrtcserverrequest }; }
        public CloseWebRtcServerRequestT AsWorker_CloseWebRtcServerRequest() { return this.As<CloseWebRtcServerRequestT>(); }
        public static BodyUnion FromWorker_CloseWebRtcServerRequest(CloseWebRtcServerRequestT _worker_closewebrtcserverrequest) { return new BodyUnion { Type = Body.Worker_CloseWebRtcServerRequest, Value = _worker_closewebrtcserverrequest }; }
        public CreateRouterRequestT AsWorker_CreateRouterRequest() { return this.As<CreateRouterRequestT>(); }
        public static BodyUnion FromWorker_CreateRouterRequest(CreateRouterRequestT _worker_createrouterrequest) { return new BodyUnion { Type = Body.Worker_CreateRouterRequest, Value = _worker_createrouterrequest }; }
        public CloseRouterRequestT AsWorker_CloseRouterRequest() { return this.As<CloseRouterRequestT>(); }
        public static BodyUnion FromWorker_CloseRouterRequest(CloseRouterRequestT _worker_closerouterrequest) { return new BodyUnion { Type = Body.Worker_CloseRouterRequest, Value = _worker_closerouterrequest }; }
        public CreateWebRtcTransportRequestT AsRouter_CreateWebRtcTransportRequest() { return this.As<CreateWebRtcTransportRequestT>(); }
        public static BodyUnion FromRouter_CreateWebRtcTransportRequest(CreateWebRtcTransportRequestT _router_createwebrtctransportrequest) { return new BodyUnion { Type = Body.Router_CreateWebRtcTransportRequest, Value = _router_createwebrtctransportrequest }; }
        public CreatePlainTransportRequestT AsRouter_CreatePlainTransportRequest() { return this.As<CreatePlainTransportRequestT>(); }
        public static BodyUnion FromRouter_CreatePlainTransportRequest(CreatePlainTransportRequestT _router_createplaintransportrequest) { return new BodyUnion { Type = Body.Router_CreatePlainTransportRequest, Value = _router_createplaintransportrequest }; }
        public CreatePipeTransportRequestT AsRouter_CreatePipeTransportRequest() { return this.As<CreatePipeTransportRequestT>(); }
        public static BodyUnion FromRouter_CreatePipeTransportRequest(CreatePipeTransportRequestT _router_createpipetransportrequest) { return new BodyUnion { Type = Body.Router_CreatePipeTransportRequest, Value = _router_createpipetransportrequest }; }
        public CreateDirectTransportRequestT AsRouter_CreateDirectTransportRequest() { return this.As<CreateDirectTransportRequestT>(); }
        public static BodyUnion FromRouter_CreateDirectTransportRequest(CreateDirectTransportRequestT _router_createdirecttransportrequest) { return new BodyUnion { Type = Body.Router_CreateDirectTransportRequest, Value = _router_createdirecttransportrequest }; }
        public CreateActiveSpeakerObserverRequestT AsRouter_CreateActiveSpeakerObserverRequest() { return this.As<CreateActiveSpeakerObserverRequestT>(); }
        public static BodyUnion FromRouter_CreateActiveSpeakerObserverRequest(CreateActiveSpeakerObserverRequestT _router_createactivespeakerobserverrequest) { return new BodyUnion { Type = Body.Router_CreateActiveSpeakerObserverRequest, Value = _router_createactivespeakerobserverrequest }; }
        public CreateAudioLevelObserverRequestT AsRouter_CreateAudioLevelObserverRequest() { return this.As<CreateAudioLevelObserverRequestT>(); }
        public static BodyUnion FromRouter_CreateAudioLevelObserverRequest(CreateAudioLevelObserverRequestT _router_createaudiolevelobserverrequest) { return new BodyUnion { Type = Body.Router_CreateAudioLevelObserverRequest, Value = _router_createaudiolevelobserverrequest }; }
        public CloseTransportRequestT AsRouter_CloseTransportRequest() { return this.As<CloseTransportRequestT>(); }
        public static BodyUnion FromRouter_CloseTransportRequest(CloseTransportRequestT _router_closetransportrequest) { return new BodyUnion { Type = Body.Router_CloseTransportRequest, Value = _router_closetransportrequest }; }
        public CloseRtpObserverRequestT AsRouter_CloseRtpObserverRequest() { return this.As<CloseRtpObserverRequestT>(); }
        public static BodyUnion FromRouter_CloseRtpObserverRequest(CloseRtpObserverRequestT _router_closertpobserverrequest) { return new BodyUnion { Type = Body.Router_CloseRtpObserverRequest, Value = _router_closertpobserverrequest }; }
        public SetMaxIncomingBitrateRequestT AsTransport_SetMaxIncomingBitrateRequest() { return this.As<SetMaxIncomingBitrateRequestT>(); }
        public static BodyUnion FromTransport_SetMaxIncomingBitrateRequest(SetMaxIncomingBitrateRequestT _transport_setmaxincomingbitraterequest) { return new BodyUnion { Type = Body.Transport_SetMaxIncomingBitrateRequest, Value = _transport_setmaxincomingbitraterequest }; }
        public SetMaxOutgoingBitrateRequestT AsTransport_SetMaxOutgoingBitrateRequest() { return this.As<SetMaxOutgoingBitrateRequestT>(); }
        public static BodyUnion FromTransport_SetMaxOutgoingBitrateRequest(SetMaxOutgoingBitrateRequestT _transport_setmaxoutgoingbitraterequest) { return new BodyUnion { Type = Body.Transport_SetMaxOutgoingBitrateRequest, Value = _transport_setmaxoutgoingbitraterequest }; }
        public SetMinOutgoingBitrateRequestT AsTransport_SetMinOutgoingBitrateRequest() { return this.As<SetMinOutgoingBitrateRequestT>(); }
        public static BodyUnion FromTransport_SetMinOutgoingBitrateRequest(SetMinOutgoingBitrateRequestT _transport_setminoutgoingbitraterequest) { return new BodyUnion { Type = Body.Transport_SetMinOutgoingBitrateRequest, Value = _transport_setminoutgoingbitraterequest }; }
        public ProduceRequestT AsTransport_ProduceRequest() { return this.As<ProduceRequestT>(); }
        public static BodyUnion FromTransport_ProduceRequest(ProduceRequestT _transport_producerequest) { return new BodyUnion { Type = Body.Transport_ProduceRequest, Value = _transport_producerequest }; }
        public ConsumeRequestT AsTransport_ConsumeRequest() { return this.As<ConsumeRequestT>(); }
        public static BodyUnion FromTransport_ConsumeRequest(ConsumeRequestT _transport_consumerequest) { return new BodyUnion { Type = Body.Transport_ConsumeRequest, Value = _transport_consumerequest }; }
        public ProduceDataRequestT AsTransport_ProduceDataRequest() { return this.As<ProduceDataRequestT>(); }
        public static BodyUnion FromTransport_ProduceDataRequest(ProduceDataRequestT _transport_producedatarequest) { return new BodyUnion { Type = Body.Transport_ProduceDataRequest, Value = _transport_producedatarequest }; }
        public ConsumeDataRequestT AsTransport_ConsumeDataRequest() { return this.As<ConsumeDataRequestT>(); }
        public static BodyUnion FromTransport_ConsumeDataRequest(ConsumeDataRequestT _transport_consumedatarequest) { return new BodyUnion { Type = Body.Transport_ConsumeDataRequest, Value = _transport_consumedatarequest }; }
        public Transport.EnableTraceEventRequestT AsTransport_EnableTraceEventRequest() { return this.As<Transport.EnableTraceEventRequestT>(); }
        public static BodyUnion FromTransport_EnableTraceEventRequest(Transport.EnableTraceEventRequestT _transport_enabletraceeventrequest) { return new BodyUnion { Type = Body.Transport_EnableTraceEventRequest, Value = _transport_enabletraceeventrequest }; }
        public CloseProducerRequestT AsTransport_CloseProducerRequest() { return this.As<CloseProducerRequestT>(); }
        public static BodyUnion FromTransport_CloseProducerRequest(CloseProducerRequestT _transport_closeproducerrequest) { return new BodyUnion { Type = Body.Transport_CloseProducerRequest, Value = _transport_closeproducerrequest }; }
        public CloseConsumerRequestT AsTransport_CloseConsumerRequest() { return this.As<CloseConsumerRequestT>(); }
        public static BodyUnion FromTransport_CloseConsumerRequest(CloseConsumerRequestT _transport_closeconsumerrequest) { return new BodyUnion { Type = Body.Transport_CloseConsumerRequest, Value = _transport_closeconsumerrequest }; }
        public CloseDataProducerRequestT AsTransport_CloseDataProducerRequest() { return this.As<CloseDataProducerRequestT>(); }
        public static BodyUnion FromTransport_CloseDataProducerRequest(CloseDataProducerRequestT _transport_closedataproducerrequest) { return new BodyUnion { Type = Body.Transport_CloseDataProducerRequest, Value = _transport_closedataproducerrequest }; }
        public CloseDataConsumerRequestT AsTransport_CloseDataConsumerRequest() { return this.As<CloseDataConsumerRequestT>(); }
        public static BodyUnion FromTransport_CloseDataConsumerRequest(CloseDataConsumerRequestT _transport_closedataconsumerrequest) { return new BodyUnion { Type = Body.Transport_CloseDataConsumerRequest, Value = _transport_closedataconsumerrequest }; }
        public ConnectRequestT AsPlainTransport_ConnectRequest() { return this.As<ConnectRequestT>(); }
        public static BodyUnion FromPlainTransport_ConnectRequest(ConnectRequestT _plaintransport_connectrequest) { return new BodyUnion { Type = Body.PlainTransport_ConnectRequest, Value = _plaintransport_connectrequest }; }
        public MediasoupSharp.FlatBuffers.PipeTransport.T.ConnectRequestT AsPipeTransport_ConnectRequest() { return this.As<MediasoupSharp.FlatBuffers.PipeTransport.T.ConnectRequestT>(); }
        public static BodyUnion FromPipeTransport_ConnectRequest(MediasoupSharp.FlatBuffers.PipeTransport.T.ConnectRequestT _pipetransport_connectrequest) { return new BodyUnion { Type = Body.PipeTransport_ConnectRequest, Value = _pipetransport_connectrequest }; }
        public MediasoupSharp.FlatBuffers.WebRtcTransport.T.ConnectRequestT AsWebRtcTransport_ConnectRequest() { return this.As<MediasoupSharp.FlatBuffers.WebRtcTransport.T.ConnectRequestT>(); }
        public static BodyUnion FromWebRtcTransport_ConnectRequest(MediasoupSharp.FlatBuffers.WebRtcTransport.T.ConnectRequestT _webrtctransport_connectrequest) { return new BodyUnion { Type = Body.WebRtcTransport_ConnectRequest, Value = _webrtctransport_connectrequest }; }
        public EnableTraceEventRequestT AsProducer_EnableTraceEventRequest() { return this.As<EnableTraceEventRequestT>(); }
        public static BodyUnion FromProducer_EnableTraceEventRequest(EnableTraceEventRequestT _producer_enabletraceeventrequest) { return new BodyUnion { Type = Body.Producer_EnableTraceEventRequest, Value = _producer_enabletraceeventrequest }; }
        public SetPreferredLayersRequestT AsConsumer_SetPreferredLayersRequest() { return this.As<SetPreferredLayersRequestT>(); }
        public static BodyUnion FromConsumer_SetPreferredLayersRequest(SetPreferredLayersRequestT _consumer_setpreferredlayersrequest) { return new BodyUnion { Type = Body.Consumer_SetPreferredLayersRequest, Value = _consumer_setpreferredlayersrequest }; }
        public SetPriorityRequestT AsConsumer_SetPriorityRequest() { return this.As<SetPriorityRequestT>(); }
        public static BodyUnion FromConsumer_SetPriorityRequest(SetPriorityRequestT _consumer_setpriorityrequest) { return new BodyUnion { Type = Body.Consumer_SetPriorityRequest, Value = _consumer_setpriorityrequest }; }
        public MediasoupSharp.FlatBuffers.Consumer.T.EnableTraceEventRequestT AsConsumer_EnableTraceEventRequest() { return this.As<MediasoupSharp.FlatBuffers.Consumer.T.EnableTraceEventRequestT>(); }
        public static BodyUnion FromConsumer_EnableTraceEventRequest(MediasoupSharp.FlatBuffers.Consumer.T.EnableTraceEventRequestT _consumer_enabletraceeventrequest) { return new BodyUnion { Type = Body.Consumer_EnableTraceEventRequest, Value = _consumer_enabletraceeventrequest }; }
        public SetBufferedAmountLowThresholdRequestT AsDataConsumer_SetBufferedAmountLowThresholdRequest() { return this.As<SetBufferedAmountLowThresholdRequestT>(); }
        public static BodyUnion FromDataConsumer_SetBufferedAmountLowThresholdRequest(SetBufferedAmountLowThresholdRequestT _dataconsumer_setbufferedamountlowthresholdrequest) { return new BodyUnion { Type = Body.DataConsumer_SetBufferedAmountLowThresholdRequest, Value = _dataconsumer_setbufferedamountlowthresholdrequest }; }
        public SendRequestT AsDataConsumer_SendRequest() { return this.As<SendRequestT>(); }
        public static BodyUnion FromDataConsumer_SendRequest(SendRequestT _dataconsumer_sendrequest) { return new BodyUnion { Type = Body.DataConsumer_SendRequest, Value = _dataconsumer_sendrequest }; }
        public SetSubchannelsRequestT AsDataConsumer_SetSubchannelsRequest() { return this.As<SetSubchannelsRequestT>(); }
        public static BodyUnion FromDataConsumer_SetSubchannelsRequest(SetSubchannelsRequestT _dataconsumer_setsubchannelsrequest) { return new BodyUnion { Type = Body.DataConsumer_SetSubchannelsRequest, Value = _dataconsumer_setsubchannelsrequest }; }
        public AddSubchannelRequestT AsDataConsumer_AddSubchannelRequest() { return this.As<AddSubchannelRequestT>(); }
        public static BodyUnion FromDataConsumer_AddSubchannelRequest(AddSubchannelRequestT _dataconsumer_addsubchannelrequest) { return new BodyUnion { Type = Body.DataConsumer_AddSubchannelRequest, Value = _dataconsumer_addsubchannelrequest }; }
        public RemoveSubchannelRequestT AsDataConsumer_RemoveSubchannelRequest() { return this.As<RemoveSubchannelRequestT>(); }
        public static BodyUnion FromDataConsumer_RemoveSubchannelRequest(RemoveSubchannelRequestT _dataconsumer_removesubchannelrequest) { return new BodyUnion { Type = Body.DataConsumer_RemoveSubchannelRequest, Value = _dataconsumer_removesubchannelrequest }; }
        public AddProducerRequestT AsRtpObserver_AddProducerRequest() { return this.As<AddProducerRequestT>(); }
        public static BodyUnion FromRtpObserver_AddProducerRequest(AddProducerRequestT _rtpobserver_addproducerrequest) { return new BodyUnion { Type = Body.RtpObserver_AddProducerRequest, Value = _rtpobserver_addproducerrequest }; }
        public RemoveProducerRequestT AsRtpObserver_RemoveProducerRequest() { return this.As<RemoveProducerRequestT>(); }
        public static BodyUnion FromRtpObserver_RemoveProducerRequest(RemoveProducerRequestT _rtpobserver_removeproducerrequest) { return new BodyUnion { Type = Body.RtpObserver_RemoveProducerRequest, Value = _rtpobserver_removeproducerrequest }; }

        public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, BodyUnion _o)
        {
            switch(_o.Type)
            {
                default:
                    return 0;
                case Body.Worker_UpdateSettingsRequest:
                    return UpdateSettingsRequest.Pack(builder, _o.AsWorker_UpdateSettingsRequest()).Value;
                case Body.Worker_CreateWebRtcServerRequest:
                    return CreateWebRtcServerRequest.Pack(builder, _o.AsWorker_CreateWebRtcServerRequest()).Value;
                case Body.Worker_CloseWebRtcServerRequest:
                    return CloseWebRtcServerRequest.Pack(builder, _o.AsWorker_CloseWebRtcServerRequest()).Value;
                case Body.Worker_CreateRouterRequest:
                    return CreateRouterRequest.Pack(builder, _o.AsWorker_CreateRouterRequest()).Value;
                case Body.Worker_CloseRouterRequest:
                    return CloseRouterRequest.Pack(builder, _o.AsWorker_CloseRouterRequest()).Value;
                case Body.Router_CreateWebRtcTransportRequest:
                    return CreateWebRtcTransportRequest.Pack(builder, _o.AsRouter_CreateWebRtcTransportRequest()).Value;
                case Body.Router_CreatePlainTransportRequest:
                    return CreatePlainTransportRequest.Pack(builder, _o.AsRouter_CreatePlainTransportRequest()).Value;
                case Body.Router_CreatePipeTransportRequest:
                    return CreatePipeTransportRequest.Pack(builder, _o.AsRouter_CreatePipeTransportRequest()).Value;
                case Body.Router_CreateDirectTransportRequest:
                    return CreateDirectTransportRequest.Pack(builder, _o.AsRouter_CreateDirectTransportRequest()).Value;
                case Body.Router_CreateActiveSpeakerObserverRequest:
                    return CreateActiveSpeakerObserverRequest.Pack(builder, _o.AsRouter_CreateActiveSpeakerObserverRequest()).Value;
                case Body.Router_CreateAudioLevelObserverRequest:
                    return CreateAudioLevelObserverRequest.Pack(builder, _o.AsRouter_CreateAudioLevelObserverRequest()).Value;
                case Body.Router_CloseTransportRequest:
                    return CloseTransportRequest.Pack(builder, _o.AsRouter_CloseTransportRequest()).Value;
                case Body.Router_CloseRtpObserverRequest:
                    return CloseRtpObserverRequest.Pack(builder, _o.AsRouter_CloseRtpObserverRequest()).Value;
                case Body.Transport_SetMaxIncomingBitrateRequest:
                    return SetMaxIncomingBitrateRequest.Pack(builder, _o.AsTransport_SetMaxIncomingBitrateRequest()).Value;
                case Body.Transport_SetMaxOutgoingBitrateRequest:
                    return SetMaxOutgoingBitrateRequest.Pack(builder, _o.AsTransport_SetMaxOutgoingBitrateRequest()).Value;
                case Body.Transport_SetMinOutgoingBitrateRequest:
                    return SetMinOutgoingBitrateRequest.Pack(builder, _o.AsTransport_SetMinOutgoingBitrateRequest()).Value;
                case Body.Transport_ProduceRequest:
                    return ProduceRequest.Pack(builder, _o.AsTransport_ProduceRequest()).Value;
                case Body.Transport_ConsumeRequest:
                    return ConsumeRequest.Pack(builder, _o.AsTransport_ConsumeRequest()).Value;
                case Body.Transport_ProduceDataRequest:
                    return ProduceDataRequest.Pack(builder, _o.AsTransport_ProduceDataRequest()).Value;
                case Body.Transport_ConsumeDataRequest:
                    return ConsumeDataRequest.Pack(builder, _o.AsTransport_ConsumeDataRequest()).Value;
                case Body.Transport_EnableTraceEventRequest:
                    return EnableTraceEventRequest.Pack(builder, _o.AsTransport_EnableTraceEventRequest()).Value;
                case Body.Transport_CloseProducerRequest:
                    return CloseProducerRequest.Pack(builder, _o.AsTransport_CloseProducerRequest()).Value;
                case Body.Transport_CloseConsumerRequest:
                    return CloseConsumerRequest.Pack(builder, _o.AsTransport_CloseConsumerRequest()).Value;
                case Body.Transport_CloseDataProducerRequest:
                    return CloseDataProducerRequest.Pack(builder, _o.AsTransport_CloseDataProducerRequest()).Value;
                case Body.Transport_CloseDataConsumerRequest:
                    return CloseDataConsumerRequest.Pack(builder, _o.AsTransport_CloseDataConsumerRequest()).Value;
                case Body.PlainTransport_ConnectRequest:
                    return ConnectRequest.Pack(builder, _o.AsPlainTransport_ConnectRequest()).Value;
                case Body.PipeTransport_ConnectRequest:
                    return PipeTransport.ConnectRequest.Pack(builder, _o.AsPipeTransport_ConnectRequest()).Value;
                case Body.WebRtcTransport_ConnectRequest:
                    return WebRtcTransport.ConnectRequest.Pack(builder, _o.AsWebRtcTransport_ConnectRequest()).Value;
                case Body.Producer_EnableTraceEventRequest:
                    return Producer.EnableTraceEventRequest.Pack(builder, _o.AsProducer_EnableTraceEventRequest()).Value;
                case Body.Consumer_SetPreferredLayersRequest:
                    return SetPreferredLayersRequest.Pack(builder, _o.AsConsumer_SetPreferredLayersRequest()).Value;
                case Body.Consumer_SetPriorityRequest:
                    return SetPriorityRequest.Pack(builder, _o.AsConsumer_SetPriorityRequest()).Value;
                case Body.Consumer_EnableTraceEventRequest:
                    return Consumer.EnableTraceEventRequest.Pack(builder, _o.AsConsumer_EnableTraceEventRequest()).Value;
                case Body.DataConsumer_SetBufferedAmountLowThresholdRequest:
                    return SetBufferedAmountLowThresholdRequest.Pack(builder, _o.AsDataConsumer_SetBufferedAmountLowThresholdRequest()).Value;
                case Body.DataConsumer_SendRequest:
                    return SendRequest.Pack(builder, _o.AsDataConsumer_SendRequest()).Value;
                case Body.DataConsumer_SetSubchannelsRequest:
                    return SetSubchannelsRequest.Pack(builder, _o.AsDataConsumer_SetSubchannelsRequest()).Value;
                case Body.DataConsumer_AddSubchannelRequest:
                    return AddSubchannelRequest.Pack(builder, _o.AsDataConsumer_AddSubchannelRequest()).Value;
                case Body.DataConsumer_RemoveSubchannelRequest:
                    return RemoveSubchannelRequest.Pack(builder, _o.AsDataConsumer_RemoveSubchannelRequest()).Value;
                case Body.RtpObserver_AddProducerRequest:
                    return AddProducerRequest.Pack(builder, _o.AsRtpObserver_AddProducerRequest()).Value;
                case Body.RtpObserver_RemoveProducerRequest:
                    return RemoveProducerRequest.Pack(builder, _o.AsRtpObserver_RemoveProducerRequest()).Value;
            }
        }
    }
}
