// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;
using FlatBuffers.Transport;
using Google.FlatBuffers;
using MediasoupSharp.FlatBuffers.PipeTransport.T;
using Tuple = FlatBuffers.Transport.Tuple;

namespace FlatBuffers.PipeTransport
{
    public struct DumpResponse : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static DumpResponse GetRootAsDumpResponse(ByteBuffer _bb) { return GetRootAsDumpResponse(_bb, new DumpResponse()); }
        public static DumpResponse GetRootAsDumpResponse(ByteBuffer _bb, DumpResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public DumpResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public Dump? Base { get { int o = __p.__offset(4); return o != 0 ? (Dump?)(new Dump()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public Tuple? Tuple { get { int o = __p.__offset(6); return o != 0 ? (Tuple?)(new Tuple()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public bool Rtx { get { int o = __p.__offset(8); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public SrtpParameters.SrtpParameters? SrtpParameters { get { int o = __p.__offset(10); return o != 0 ? (SrtpParameters.SrtpParameters?)(new SrtpParameters.SrtpParameters()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<DumpResponse> CreateDumpResponse(FlatBufferBuilder builder,
                                                              Offset<Dump> @baseOffset = default(Offset<Dump>),
                                                              Offset<Tuple> tupleOffset = default(Offset<Tuple>),
                                                              bool rtx = false,
                                                              Offset<SrtpParameters.SrtpParameters> srtp_parametersOffset = default(Offset<SrtpParameters.SrtpParameters>))
        {
            builder.StartTable(4);
            DumpResponse.AddSrtpParameters(builder, srtp_parametersOffset);
            DumpResponse.AddTuple(builder, tupleOffset);
            DumpResponse.AddBase(builder, @baseOffset);
            DumpResponse.AddRtx(builder, rtx);
            return DumpResponse.EndDumpResponse(builder);
        }

        public static void StartDumpResponse(FlatBufferBuilder builder) { builder.StartTable(4); }
        public static void AddBase(FlatBufferBuilder builder, Offset<Dump> baseOffset) { builder.AddOffset(0, baseOffset.Value, 0); }
        public static void AddTuple(FlatBufferBuilder builder, Offset<Tuple> tupleOffset) { builder.AddOffset(1, tupleOffset.Value, 0); }
        public static void AddRtx(FlatBufferBuilder builder, bool rtx) { builder.AddBool(2, rtx, false); }
        public static void AddSrtpParameters(FlatBufferBuilder builder, Offset<SrtpParameters.SrtpParameters> srtpParametersOffset) { builder.AddOffset(3, srtpParametersOffset.Value, 0); }
        public static Offset<DumpResponse> EndDumpResponse(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // base
            builder.Required(o, 6);  // tuple
            return new Offset<DumpResponse>(o);
        }
        public DumpResponseT UnPack()
        {
            var _o = new DumpResponseT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(DumpResponseT _o)
        {
            _o.Base = this.Base.HasValue ? this.Base.Value.UnPack() : null;
            _o.Tuple = this.Tuple.HasValue ? this.Tuple.Value.UnPack() : null;
            _o.Rtx = this.Rtx;
            _o.SrtpParameters = this.SrtpParameters.HasValue ? this.SrtpParameters.Value.UnPack() : null;
        }
        public static Offset<DumpResponse> Pack(FlatBufferBuilder builder, DumpResponseT _o)
        {
            if(_o == null)
                return default(Offset<DumpResponse>);
            var _base = _o.Base == null ? default(Offset<Dump>) : Dump.Pack(builder, _o.Base);
            var _tuple = _o.Tuple == null ? default(Offset<Tuple>) : Transport.Tuple.Pack(builder, _o.Tuple);
            var _srtp_parameters = _o.SrtpParameters == null ? default(Offset<SrtpParameters.SrtpParameters>) : FlatBuffers.SrtpParameters.SrtpParameters.Pack(builder, _o.SrtpParameters);
            return CreateDumpResponse(
              builder,
              _base,
              _tuple,
              _o.Rtx,
              _srtp_parameters);
        }
    }
}
