// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FlatBuffers.Transport
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum BweType : byte
    {
        [EnumMember(Value = "transport-cc")]
        TRANSPORT_CC = 0,

        [EnumMember(Value = "remb")]
        REMB = 1,
    }
}
