// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FlatBuffers.Transport
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum TraceEventType : byte
    {
        [EnumMember(Value = "probation")]
        PROBATION = 0,

        [EnumMember(Value = "bwe")]
        BWE = 1,
    }
}
