// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FlatBuffers.Transport
{
    public enum TraceInfo : byte
    {
        NONE = 0,

        BweTraceInfo = 1,
    }

    public class TraceInfoUnion
    {
        public TraceInfo Type { get; set; }
        public object Value { get; set; }

        public TraceInfoUnion()
        {
            this.Type = TraceInfo.NONE;
            this.Value = null;
        }

        public T As<T>() where T : class { return this.Value as T; }
        public BweTraceInfoT AsBweTraceInfo() { return this.As<BweTraceInfoT>(); }
        public static TraceInfoUnion FromBweTraceInfo(BweTraceInfoT _bwetraceinfo) { return new TraceInfoUnion { Type = TraceInfo.BweTraceInfo, Value = _bwetraceinfo }; }

        public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, TraceInfoUnion _o)
        {
            switch(_o.Type)
            {
                default:
                    return 0;
                case TraceInfo.BweTraceInfo:
                    return BweTraceInfo.Pack(builder, _o.AsBweTraceInfo()).Value;
            }
        }
    }
}
