// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using Google.FlatBuffers;
using MediasoupSharp.FlatBuffers.WebRtcTransport.T;

namespace FlatBuffers.WebRtcTransport
{
    public struct ConnectRequest : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static ConnectRequest GetRootAsConnectRequest(ByteBuffer _bb) { return GetRootAsConnectRequest(_bb, new ConnectRequest()); }
        public static ConnectRequest GetRootAsConnectRequest(ByteBuffer _bb, ConnectRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public ConnectRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public DtlsParameters? DtlsParameters { get { int o = __p.__offset(4); return o != 0 ? (DtlsParameters?)(new DtlsParameters()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<ConnectRequest> CreateConnectRequest(FlatBufferBuilder builder,
                                                                  Offset<DtlsParameters> dtls_parametersOffset = default(Offset<DtlsParameters>))
        {
            builder.StartTable(1);
            ConnectRequest.AddDtlsParameters(builder, dtls_parametersOffset);
            return ConnectRequest.EndConnectRequest(builder);
        }

        public static void StartConnectRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddDtlsParameters(FlatBufferBuilder builder, Offset<DtlsParameters> dtlsParametersOffset) { builder.AddOffset(0, dtlsParametersOffset.Value, 0); }
        public static Offset<ConnectRequest> EndConnectRequest(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // dtls_parameters
            return new Offset<ConnectRequest>(o);
        }
        public ConnectRequestT UnPack()
        {
            var _o = new ConnectRequestT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ConnectRequestT _o)
        {
            _o.DtlsParameters = this.DtlsParameters.HasValue ? this.DtlsParameters.Value.UnPack() : null;
        }
        public static Offset<ConnectRequest> Pack(FlatBufferBuilder builder, ConnectRequestT _o)
        {
            if(_o == null)
                return default(Offset<ConnectRequest>);
            var _dtls_parameters = _o.DtlsParameters == null ? default(Offset<DtlsParameters>) : WebRtcTransport.DtlsParameters.Pack(builder, _o.DtlsParameters);
            return CreateConnectRequest(
              builder,
              _dtls_parameters);
        }
    }
}
