// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using Google.FlatBuffers;
using System.Text.Json.Serialization;
using FlatBuffers.Transport;
using MediasoupSharp.FlatBuffers.WebRtcTransport.T;
using Tuple = FlatBuffers.Transport.Tuple;

namespace FlatBuffers.WebRtcTransport
{
    public struct GetStatsResponse : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static GetStatsResponse GetRootAsGetStatsResponse(ByteBuffer _bb) { return GetRootAsGetStatsResponse(_bb, new GetStatsResponse()); }
        public static GetStatsResponse GetRootAsGetStatsResponse(ByteBuffer _bb, GetStatsResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public GetStatsResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public Stats? Base { get { int o = __p.__offset(4); return o != 0 ? (Stats?)(new Stats()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public IceRole IceRole { get { int o = __p.__offset(6); return o != 0 ? (IceRole)__p.bb.Get(o + __p.bb_pos) : IceRole.CONTROLLED; } }
        public IceState IceState { get { int o = __p.__offset(8); return o != 0 ? (IceState)__p.bb.Get(o + __p.bb_pos) : IceState.NEW; } }
        public Tuple? IceSelectedTuple { get { int o = __p.__offset(10); return o != 0 ? (Tuple?)(new Tuple()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public DtlsState DtlsState { get { int o = __p.__offset(12); return o != 0 ? (DtlsState)__p.bb.Get(o + __p.bb_pos) : DtlsState.NEW; } }

        public static Offset<GetStatsResponse> CreateGetStatsResponse(FlatBufferBuilder builder,
                                                                      Offset<Stats> @baseOffset = default(Offset<Stats>),
                                                                      IceRole ice_role = IceRole.CONTROLLED,
                                                                      IceState ice_state = IceState.NEW,
                                                                      Offset<Tuple> ice_selected_tupleOffset = default(Offset<Tuple>),
                                                                      DtlsState dtls_state = DtlsState.NEW)
        {
            builder.StartTable(5);
            GetStatsResponse.AddIceSelectedTuple(builder, ice_selected_tupleOffset);
            GetStatsResponse.AddBase(builder, @baseOffset);
            GetStatsResponse.AddDtlsState(builder, dtls_state);
            GetStatsResponse.AddIceState(builder, ice_state);
            GetStatsResponse.AddIceRole(builder, ice_role);
            return GetStatsResponse.EndGetStatsResponse(builder);
        }

        public static void StartGetStatsResponse(FlatBufferBuilder builder) { builder.StartTable(5); }
        public static void AddBase(FlatBufferBuilder builder, Offset<Stats> baseOffset) { builder.AddOffset(0, baseOffset.Value, 0); }
        public static void AddIceRole(FlatBufferBuilder builder, IceRole iceRole) { builder.AddByte(1, (byte)iceRole, 0); }
        public static void AddIceState(FlatBufferBuilder builder, IceState iceState) { builder.AddByte(2, (byte)iceState, 0); }
        public static void AddIceSelectedTuple(FlatBufferBuilder builder, Offset<Tuple> iceSelectedTupleOffset) { builder.AddOffset(3, iceSelectedTupleOffset.Value, 0); }
        public static void AddDtlsState(FlatBufferBuilder builder, DtlsState dtlsState) { builder.AddByte(4, (byte)dtlsState, 0); }
        public static Offset<GetStatsResponse> EndGetStatsResponse(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // base
            return new Offset<GetStatsResponse>(o);
        }
        public GetStatsResponseT UnPack()
        {
            var _o = new GetStatsResponseT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(GetStatsResponseT _o)
        {
            _o.Base = this.Base.HasValue ? this.Base.Value.UnPack() : null;
            _o.IceRole = this.IceRole;
            _o.IceState = this.IceState;
            _o.IceSelectedTuple = this.IceSelectedTuple.HasValue ? this.IceSelectedTuple.Value.UnPack() : null;
            _o.DtlsState = this.DtlsState;
        }
        public static Offset<GetStatsResponse> Pack(FlatBufferBuilder builder, GetStatsResponseT _o)
        {
            if(_o == null)
                return default(Offset<GetStatsResponse>);
            var _base = _o.Base == null ? default(Offset<Stats>) : Stats.Pack(builder, _o.Base);
            var _ice_selected_tuple = _o.IceSelectedTuple == null ? default(Offset<Tuple>) : Tuple.Pack(builder, _o.IceSelectedTuple);
            return CreateGetStatsResponse(
              builder,
              _base,
              _o.IceRole,
              _o.IceState,
              _ice_selected_tuple,
              _o.DtlsState);
        }
    }
}
