// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FlatBuffers.WebRtcTransport
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum IceRole : byte
    {
        [EnumMember(Value = "controlled")]
        CONTROLLED = 0,

        [EnumMember(Value = "controlling")]
        CONTROLLING = 1,
    }
}
