// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace FlatBuffers.Common
{
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum TraceDirection : byte
    {
        [EnumMember(Value = "in")] DIRECTION_IN = 0,

        [EnumMember(Value = "out")] DIRECTION_OUT = 1,
    };
}
