// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;
using Google.FlatBuffers;

namespace FlatBuffers.RtpStream
{
    public class SendStatsT
    {
        public StatsT Base { get; set; }

        public ulong PacketCount { get; set; }

        public ulong ByteCount { get; set; }

        public uint Bitrate { get; set; }
    }
}
