// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using Google.FlatBuffers;
using System.Text.Json.Serialization;

namespace FlatBuffers.SrtpParameters
{
    public class SrtpParametersT
    {
        public SrtpCryptoSuite CryptoSuite { get; set; }

        public string KeyBase64 { get; set; }
    }
}
