// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using FlatBuffers.DirectTransport;
using MediasoupSharp.FlatBuffers.DirectTransport.T;

namespace FlatBuffers.Router
{

  using System;
  using System.Collections.Generic;
  using Google.FlatBuffers;
  using System.Text.Json.Serialization;

  public struct CreateDirectTransportRequest : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
    public static CreateDirectTransportRequest GetRootAsCreateDirectTransportRequest( ByteBuffer _bb ) { return GetRootAsCreateDirectTransportRequest( _bb, new CreateDirectTransportRequest() ); }
    public static CreateDirectTransportRequest GetRootAsCreateDirectTransportRequest( ByteBuffer _bb, CreateDirectTransportRequest obj ) { return (obj.__assign( _bb.GetInt( _bb.Position ) + _bb.Position, _bb )); }
    public void __init( int _i, ByteBuffer _bb ) { __p = new Table( _i, _bb ); }
    public CreateDirectTransportRequest __assign( int _i, ByteBuffer _bb ) { __init( _i, _bb ); return this; }

    public string TransportId { get { int o = __p.__offset( 4 ); return o != 0 ? __p.__string( o + __p.bb_pos ) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTransportIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
    public ArraySegment<byte>? GetTransportIdBytes() { return __p.__vector_as_arraysegment( 4 ); }
#endif
    public byte[] GetTransportIdArray() { return __p.__vector_as_array<byte>( 4 ); }
    public DirectTransportOptions? Options { get { int o = __p.__offset( 6 ); return o != 0 ? ( DirectTransportOptions? ) (new DirectTransportOptions()).__assign( __p.__indirect( o + __p.bb_pos ), __p.bb ) : null; } }

    public static Offset<CreateDirectTransportRequest> CreateCreateDirectTransportRequest( FlatBufferBuilder builder,
                                                                                           StringOffset transport_idOffset = default( StringOffset ),
                                                                                           Offset<DirectTransportOptions> optionsOffset = default( Offset<DirectTransportOptions> ) )
    {
      builder.StartTable( 2 );
      CreateDirectTransportRequest.AddOptions( builder, optionsOffset );
      CreateDirectTransportRequest.AddTransportId( builder, transport_idOffset );
      return CreateDirectTransportRequest.EndCreateDirectTransportRequest( builder );
    }

    public static void StartCreateDirectTransportRequest( FlatBufferBuilder builder ) { builder.StartTable( 2 ); }
    public static void AddTransportId( FlatBufferBuilder builder, StringOffset transportIdOffset ) { builder.AddOffset( 0, transportIdOffset.Value, 0 ); }
    public static void AddOptions( FlatBufferBuilder builder, Offset<DirectTransportOptions> optionsOffset ) { builder.AddOffset( 1, optionsOffset.Value, 0 ); }
    public static Offset<CreateDirectTransportRequest> EndCreateDirectTransportRequest( FlatBufferBuilder builder )
    {
      int o = builder.EndTable();
      builder.Required( o, 4 );  // transport_id
      builder.Required( o, 6 );  // options
      return new Offset<CreateDirectTransportRequest>( o );
    }
    public CreateDirectTransportRequestT UnPack()
    {
      var _o = new CreateDirectTransportRequestT();
      this.UnPackTo( _o );
      return _o;
    }
    public void UnPackTo( CreateDirectTransportRequestT _o )
    {
      _o.TransportId = this.TransportId;
      _o.Options = this.Options.HasValue ? this.Options.Value.UnPack() : null;
    }
    public static Offset<CreateDirectTransportRequest> Pack( FlatBufferBuilder builder, CreateDirectTransportRequestT _o )
    {
      if ( _o == null )
        return default( Offset<CreateDirectTransportRequest> );
      var _transport_id = _o.TransportId == null ? default( StringOffset ) : builder.CreateString( _o.TransportId );
      var _options = _o.Options == null ? default( Offset<DirectTransportOptions> ) : DirectTransportOptions.Pack( builder, _o.Options );
      return CreateCreateDirectTransportRequest(
        builder,
        _transport_id,
        _options );
    }
  }

  public class CreateDirectTransportRequestT
  {
    [JsonPropertyName( "transport_id" )]
    public string TransportId { get; set; }
    [JsonPropertyName( "options" )]
    public DirectTransportOptionsT Options { get; set; }

    public CreateDirectTransportRequestT()
    {
      this.TransportId = null;
      this.Options = null;
    }
  }


}
