// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using System.Text.Json.Serialization;
using Google.FlatBuffers;

namespace FlatBuffers.Transport
{
    public class TupleT
    {
        public string LocalIp { get; set; }

        public ushort LocalPort { get; set; }

        public string RemoteIp { get; set; }

        public ushort RemotePort { get; set; }

        public Protocol Protocol { get; set; }
    }
}
