// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>


using FlatBuffers.ActiveSpeakerObserver;
using FlatBuffers.AudioLevelObserver;
using FlatBuffers.Consumer;
using FlatBuffers.DataConsumer;
using FlatBuffers.DirectTransport;
using FlatBuffers.PlainTransport;
using FlatBuffers.Producer;
using FlatBuffers.Transport;
using FlatBuffers.WebRtcTransport;
using MediasoupSharp.FlatBuffers.ActiveSpeakerObserver.T;
using MediasoupSharp.FlatBuffers.Consumer;
using MediasoupSharp.FlatBuffers.Consumer.T;
using MediasoupSharp.FlatBuffers.DataConsumer.T;
using MediasoupSharp.FlatBuffers.DirectTransport.T;
using MediasoupSharp.FlatBuffers.PlainTransport.T;
using MediasoupSharp.FlatBuffers.Producer.T;
using MediasoupSharp.FlatBuffers.Transport.T;
using MediasoupSharp.FlatBuffers.WebRtcTransport.T;
using ScoreNotification = FlatBuffers.Producer.ScoreNotification;
using ScoreNotificationT = MediasoupSharp.FlatBuffers.Producer.T.ScoreNotificationT;
using TraceNotification = FlatBuffers.Transport.TraceNotification;
using TraceNotificationT = MediasoupSharp.FlatBuffers.Producer.T.TraceNotificationT;

namespace FlatBuffers.Notification
{
    public enum Body : byte
    {
        NONE = 0,
        Transport_SendRtcpNotification = 1,
        Transport_SctpStateChangeNotification = 2,
        Producer_SendNotification = 3,
        DataProducer_SendNotification = 4,
        Transport_TraceNotification = 5,
        WebRtcTransport_IceSelectedTupleChangeNotification = 6,
        WebRtcTransport_IceStateChangeNotification = 7,
        WebRtcTransport_DtlsStateChangeNotification = 8,
        PlainTransport_TupleNotification = 9,
        PlainTransport_RtcpTupleNotification = 10,
        DirectTransport_RtcpNotification = 11,
        Producer_ScoreNotification = 12,
        Producer_TraceNotification = 13,
        Producer_VideoOrientationChangeNotification = 14,
        Consumer_LayersChangeNotification = 15,
        Consumer_RtpNotification = 16,
        Consumer_ScoreNotification = 17,
        Consumer_TraceNotification = 18,
        DataConsumer_MessageNotification = 19,
        DataConsumer_BufferedAmountLowNotification = 20,
        ActiveSpeakerObserver_DominantSpeakerNotification = 21,
        AudioLevelObserver_VolumesNotification = 22,
    };

    public class BodyUnion
    {
        public Body Type { get; set; }
        public object Value { get; set; }

        public BodyUnion()
        {
            this.Type = Body.NONE;
            this.Value = null;
        }

        public T As<T>() where T : class { return this.Value as T; }
        public SendRtcpNotificationT AsTransport_SendRtcpNotification() { return this.As<SendRtcpNotificationT>(); }
        public static BodyUnion FromTransport_SendRtcpNotification(SendRtcpNotificationT _transport_sendrtcpnotification) { return new BodyUnion { Type = Body.Transport_SendRtcpNotification, Value = _transport_sendrtcpnotification }; }
        public SctpStateChangeNotificationT AsTransport_SctpStateChangeNotification() { return this.As<SctpStateChangeNotificationT>(); }
        public static BodyUnion FromTransport_SctpStateChangeNotification(SctpStateChangeNotificationT _transport_sctpstatechangenotification) { return new BodyUnion { Type = Body.Transport_SctpStateChangeNotification, Value = _transport_sctpstatechangenotification }; }
        public SendNotificationT AsProducer_SendNotification() { return this.As<SendNotificationT>(); }
        public static BodyUnion FromProducer_SendNotification(SendNotificationT _producer_sendnotification) { return new BodyUnion { Type = Body.Producer_SendNotification, Value = _producer_sendnotification }; }
        public MediasoupSharp.FlatBuffers.DataProducer.T.SendNotificationT AsDataProducer_SendNotification() { return this.As<MediasoupSharp.FlatBuffers.DataProducer.T.SendNotificationT>(); }
        public static BodyUnion FromDataProducer_SendNotification(MediasoupSharp.FlatBuffers.DataProducer.T.SendNotificationT _dataproducer_sendnotification) { return new BodyUnion { Type = Body.DataProducer_SendNotification, Value = _dataproducer_sendnotification }; }
        public Transport.TraceNotificationT AsTransport_TraceNotification() { return this.As<Transport.TraceNotificationT>(); }
        public static BodyUnion FromTransport_TraceNotification(Transport.TraceNotificationT _transport_tracenotification) { return new BodyUnion { Type = Body.Transport_TraceNotification, Value = _transport_tracenotification }; }
        public IceSelectedTupleChangeNotificationT AsWebRtcTransport_IceSelectedTupleChangeNotification() { return this.As<IceSelectedTupleChangeNotificationT>(); }
        public static BodyUnion FromWebRtcTransport_IceSelectedTupleChangeNotification(IceSelectedTupleChangeNotificationT _webrtctransport_iceselectedtuplechangenotification) { return new BodyUnion { Type = Body.WebRtcTransport_IceSelectedTupleChangeNotification, Value = _webrtctransport_iceselectedtuplechangenotification }; }
        public IceStateChangeNotificationT AsWebRtcTransport_IceStateChangeNotification() { return this.As<IceStateChangeNotificationT>(); }
        public static BodyUnion FromWebRtcTransport_IceStateChangeNotification(IceStateChangeNotificationT _webrtctransport_icestatechangenotification) { return new BodyUnion { Type = Body.WebRtcTransport_IceStateChangeNotification, Value = _webrtctransport_icestatechangenotification }; }
        public DtlsStateChangeNotificationT AsWebRtcTransport_DtlsStateChangeNotification() { return this.As<DtlsStateChangeNotificationT>(); }
        public static BodyUnion FromWebRtcTransport_DtlsStateChangeNotification(DtlsStateChangeNotificationT _webrtctransport_dtlsstatechangenotification) { return new BodyUnion { Type = Body.WebRtcTransport_DtlsStateChangeNotification, Value = _webrtctransport_dtlsstatechangenotification }; }
        public TupleNotificationT AsPlainTransport_TupleNotification() { return this.As<TupleNotificationT>(); }
        public static BodyUnion FromPlainTransport_TupleNotification(TupleNotificationT _plaintransport_tuplenotification) { return new BodyUnion { Type = Body.PlainTransport_TupleNotification, Value = _plaintransport_tuplenotification }; }
        public RtcpTupleNotificationT AsPlainTransport_RtcpTupleNotification() { return this.As<RtcpTupleNotificationT>(); }
        public static BodyUnion FromPlainTransport_RtcpTupleNotification(RtcpTupleNotificationT _plaintransport_rtcptuplenotification) { return new BodyUnion { Type = Body.PlainTransport_RtcpTupleNotification, Value = _plaintransport_rtcptuplenotification }; }
        public RtcpNotificationT AsDirectTransport_RtcpNotification() { return this.As<RtcpNotificationT>(); }
        public static BodyUnion FromDirectTransport_RtcpNotification(RtcpNotificationT _directtransport_rtcpnotification) { return new BodyUnion { Type = Body.DirectTransport_RtcpNotification, Value = _directtransport_rtcpnotification }; }
        public ScoreNotificationT AsProducer_ScoreNotification() { return this.As<ScoreNotificationT>(); }
        public static BodyUnion FromProducer_ScoreNotification(ScoreNotificationT _producer_scorenotification) { return new BodyUnion { Type = Body.Producer_ScoreNotification, Value = _producer_scorenotification }; }
        public TraceNotificationT AsProducer_TraceNotification() { return this.As<TraceNotificationT>(); }
        public static BodyUnion FromProducer_TraceNotification(TraceNotificationT _producer_tracenotification) { return new BodyUnion { Type = Body.Producer_TraceNotification, Value = _producer_tracenotification }; }
        public VideoOrientationChangeNotificationT AsProducer_VideoOrientationChangeNotification() { return this.As<VideoOrientationChangeNotificationT>(); }
        public static BodyUnion FromProducer_VideoOrientationChangeNotification(VideoOrientationChangeNotificationT _producer_videoorientationchangenotification) { return new BodyUnion { Type = Body.Producer_VideoOrientationChangeNotification, Value = _producer_videoorientationchangenotification }; }
        public LayersChangeNotificationT AsConsumer_LayersChangeNotification() { return this.As<LayersChangeNotificationT>(); }
        public static BodyUnion FromConsumer_LayersChangeNotification(LayersChangeNotificationT _consumer_layerschangenotification) { return new BodyUnion { Type = Body.Consumer_LayersChangeNotification, Value = _consumer_layerschangenotification }; }
        public RtpNotificationT AsConsumer_RtpNotification() { return this.As<RtpNotificationT>(); }
        public static BodyUnion FromConsumer_RtpNotification(RtpNotificationT _consumer_rtpnotification) { return new BodyUnion { Type = Body.Consumer_RtpNotification, Value = _consumer_rtpnotification }; }
        public MediasoupSharp.FlatBuffers.Consumer.T.ScoreNotificationT AsConsumer_ScoreNotification() { return this.As<MediasoupSharp.FlatBuffers.Consumer.T.ScoreNotificationT>(); }
        public static BodyUnion FromConsumer_ScoreNotification(MediasoupSharp.FlatBuffers.Consumer.T.ScoreNotificationT _consumer_scorenotification) { return new BodyUnion { Type = Body.Consumer_ScoreNotification, Value = _consumer_scorenotification }; }
        public Consumer.TraceNotificationT AsConsumer_TraceNotification() { return this.As<Consumer.TraceNotificationT>(); }
        public static BodyUnion FromConsumer_TraceNotification(Consumer.TraceNotificationT _consumer_tracenotification) { return new BodyUnion { Type = Body.Consumer_TraceNotification, Value = _consumer_tracenotification }; }
        public MessageNotificationT AsDataConsumer_MessageNotification() { return this.As<MessageNotificationT>(); }
        public static BodyUnion FromDataConsumer_MessageNotification(MessageNotificationT _dataconsumer_messagenotification) { return new BodyUnion { Type = Body.DataConsumer_MessageNotification, Value = _dataconsumer_messagenotification }; }
        public BufferedAmountLowNotificationT AsDataConsumer_BufferedAmountLowNotification() { return this.As<BufferedAmountLowNotificationT>(); }
        public static BodyUnion FromDataConsumer_BufferedAmountLowNotification(BufferedAmountLowNotificationT _dataconsumer_bufferedamountlownotification) { return new BodyUnion { Type = Body.DataConsumer_BufferedAmountLowNotification, Value = _dataconsumer_bufferedamountlownotification }; }
        public DominantSpeakerNotificationT AsActiveSpeakerObserver_DominantSpeakerNotification() { return this.As<DominantSpeakerNotificationT>(); }
        public static BodyUnion FromActiveSpeakerObserver_DominantSpeakerNotification(DominantSpeakerNotificationT _activespeakerobserver_dominantspeakernotification) { return new BodyUnion { Type = Body.ActiveSpeakerObserver_DominantSpeakerNotification, Value = _activespeakerobserver_dominantspeakernotification }; }
        public VolumesNotificationT AsAudioLevelObserver_VolumesNotification() { return this.As<VolumesNotificationT>(); }
        public static BodyUnion FromAudioLevelObserver_VolumesNotification(VolumesNotificationT _audiolevelobserver_volumesnotification) { return new BodyUnion { Type = Body.AudioLevelObserver_VolumesNotification, Value = _audiolevelobserver_volumesnotification }; }

        public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, BodyUnion _o)
        {
            switch(_o.Type)
            {
                default:
                    return 0;
                case Body.Transport_SendRtcpNotification:
                    return SendRtcpNotification.Pack(builder, _o.AsTransport_SendRtcpNotification()).Value;
                case Body.Transport_SctpStateChangeNotification:
                    return SctpStateChangeNotification.Pack(builder, _o.AsTransport_SctpStateChangeNotification()).Value;
                case Body.Producer_SendNotification:
                    return SendNotification.Pack(builder, _o.AsProducer_SendNotification()).Value;
                case Body.DataProducer_SendNotification:
                    return DataProducer.SendNotification.Pack(builder, _o.AsDataProducer_SendNotification()).Value;
                case Body.Transport_TraceNotification:
                    return TraceNotification.Pack(builder, _o.AsTransport_TraceNotification()).Value;
                case Body.WebRtcTransport_IceSelectedTupleChangeNotification:
                    return IceSelectedTupleChangeNotification.Pack(builder, _o.AsWebRtcTransport_IceSelectedTupleChangeNotification()).Value;
                case Body.WebRtcTransport_IceStateChangeNotification:
                    return IceStateChangeNotification.Pack(builder, _o.AsWebRtcTransport_IceStateChangeNotification()).Value;
                case Body.WebRtcTransport_DtlsStateChangeNotification:
                    return DtlsStateChangeNotification.Pack(builder, _o.AsWebRtcTransport_DtlsStateChangeNotification()).Value;
                case Body.PlainTransport_TupleNotification:
                    return TupleNotification.Pack(builder, _o.AsPlainTransport_TupleNotification()).Value;
                case Body.PlainTransport_RtcpTupleNotification:
                    return RtcpTupleNotification.Pack(builder, _o.AsPlainTransport_RtcpTupleNotification()).Value;
                case Body.DirectTransport_RtcpNotification:
                    return RtcpNotification.Pack(builder, _o.AsDirectTransport_RtcpNotification()).Value;
                case Body.Producer_ScoreNotification:
                    return ScoreNotification.Pack(builder, _o.AsProducer_ScoreNotification()).Value;
                case Body.Producer_TraceNotification:
                    return Producer.TraceNotification.Pack(builder, _o.AsProducer_TraceNotification()).Value;
                case Body.Producer_VideoOrientationChangeNotification:
                    return VideoOrientationChangeNotification.Pack(builder, _o.AsProducer_VideoOrientationChangeNotification()).Value;
                case Body.Consumer_LayersChangeNotification:
                    return LayersChangeNotification.Pack(builder, _o.AsConsumer_LayersChangeNotification()).Value;
                case Body.Consumer_RtpNotification:
                    return RtpNotification.Pack(builder, _o.AsConsumer_RtpNotification()).Value;
                case Body.Consumer_ScoreNotification:
                    return Consumer.ScoreNotification.Pack(builder, _o.AsConsumer_ScoreNotification()).Value;
                case Body.Consumer_TraceNotification:
                    return Consumer.TraceNotification.Pack(builder, _o.AsConsumer_TraceNotification()).Value;
                case Body.DataConsumer_MessageNotification:
                    return MessageNotification.Pack(builder, _o.AsDataConsumer_MessageNotification()).Value;
                case Body.DataConsumer_BufferedAmountLowNotification:
                    return BufferedAmountLowNotification.Pack(builder, _o.AsDataConsumer_BufferedAmountLowNotification()).Value;
                case Body.ActiveSpeakerObserver_DominantSpeakerNotification:
                    return DominantSpeakerNotification.Pack(builder, _o.AsActiveSpeakerObserver_DominantSpeakerNotification()).Value;
                case Body.AudioLevelObserver_VolumesNotification:
                    return VolumesNotification.Pack(builder, _o.AsAudioLevelObserver_VolumesNotification()).Value;
            }
        }
    }
}
