// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using System.Collections.Generic;
using Google.FlatBuffers;
using System.Text.Json.Serialization;
using MediasoupSharp.FlatBuffers.Producer.T;

namespace FlatBuffers.Producer
{
    public struct ScoreNotification : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static ScoreNotification GetRootAsScoreNotification(ByteBuffer _bb) { return GetRootAsScoreNotification(_bb, new ScoreNotification()); }
        public static ScoreNotification GetRootAsScoreNotification(ByteBuffer _bb, ScoreNotification obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public ScoreNotification __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public Score? Scores(int j) { int o = __p.__offset(4); return o != 0 ? (Score?)(new Score()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int ScoresLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static Offset<ScoreNotification> CreateScoreNotification(FlatBufferBuilder builder,
                                                                        VectorOffset scoresOffset = default(VectorOffset))
        {
            builder.StartTable(1);
            ScoreNotification.AddScores(builder, scoresOffset);
            return ScoreNotification.EndScoreNotification(builder);
        }

        public static void StartScoreNotification(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddScores(FlatBufferBuilder builder, VectorOffset scoresOffset) { builder.AddOffset(0, scoresOffset.Value, 0); }
        public static VectorOffset CreateScoresVector(FlatBufferBuilder builder, Offset<Score>[] data) { builder.StartVector(4, data.Length, 4); for(int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateScoresVectorBlock(FlatBufferBuilder builder, Offset<Score>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateScoresVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Score>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
        public static VectorOffset CreateScoresVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Score>>(dataPtr, sizeInBytes); return builder.EndVector(); }
        public static void StartScoresVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<ScoreNotification> EndScoreNotification(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // scores
            return new Offset<ScoreNotification>(o);
        }
        public ScoreNotificationT UnPack()
        {
            var _o = new ScoreNotificationT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(ScoreNotificationT _o)
        {
            _o.Scores = new List<ScoreT>();
            for(var _j = 0; _j < this.ScoresLength; ++_j)
            { _o.Scores.Add(this.Scores(_j).HasValue ? this.Scores(_j).Value.UnPack() : null); }
        }
        public static Offset<ScoreNotification> Pack(FlatBufferBuilder builder, ScoreNotificationT _o)
        {
            if(_o == null)
                return default(Offset<ScoreNotification>);
            var _scores = default(VectorOffset);
            if(_o.Scores != null)
            {
                var __scores = new Offset<Score>[_o.Scores.Count];
                for(var _j = 0; _j < __scores.Length; ++_j)
                { __scores[_j] = Score.Pack(builder, _o.Scores[_j]); }
                _scores = CreateScoresVector(builder, __scores);
            }
            return CreateScoreNotification(
              builder,
              _scores);
        }
    }
}
