// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using FlatBuffers.Consumer;
using FlatBuffers.DataConsumer;
using FlatBuffers.PlainTransport;
using FlatBuffers.Transport;
using FlatBuffers.Worker;
using MediasoupSharp.FlatBuffers.Consumer.T;
using MediasoupSharp.FlatBuffers.DataConsumer.T;
using MediasoupSharp.FlatBuffers.PlainTransport.T;
using MediasoupSharp.FlatBuffers.Worker.T;
using DumpResponse = FlatBuffers.Worker.DumpResponse;
using DumpResponseT = MediasoupSharp.FlatBuffers.Worker.T.DumpResponseT;
using GetStatsResponse = FlatBuffers.PlainTransport.GetStatsResponse;
using GetStatsResponseT = MediasoupSharp.FlatBuffers.PlainTransport.T.GetStatsResponseT;

namespace FlatBuffers.Response
{
    public enum Body : byte
    {
        NONE                                   = 0,
        Worker_DumpResponse                    = 1,
        Worker_ResourceUsageResponse           = 2,
        WebRtcServer_DumpResponse              = 3,
        Router_DumpResponse                    = 4,
        Transport_ProduceResponse              = 5,
        Transport_ConsumeResponse              = 6,
        Transport_RestartIceResponse           = 7,
        PlainTransport_ConnectResponse         = 8,
        PlainTransport_DumpResponse            = 9,
        PlainTransport_GetStatsResponse        = 10,
        PipeTransport_ConnectResponse          = 11,
        PipeTransport_DumpResponse             = 12,
        PipeTransport_GetStatsResponse         = 13,
        DirectTransport_DumpResponse           = 14,
        DirectTransport_GetStatsResponse       = 15,
        WebRtcTransport_ConnectResponse        = 16,
        WebRtcTransport_DumpResponse           = 17,
        WebRtcTransport_GetStatsResponse       = 18,
        Producer_DumpResponse                  = 19,
        Producer_GetStatsResponse              = 20,
        Consumer_DumpResponse                  = 21,
        Consumer_GetStatsResponse              = 22,
        Consumer_SetPreferredLayersResponse    = 23,
        Consumer_SetPriorityResponse           = 24,
        DataProducer_DumpResponse              = 25,
        DataProducer_GetStatsResponse          = 26,
        DataConsumer_GetBufferedAmountResponse = 27,
        DataConsumer_DumpResponse              = 28,
        DataConsumer_GetStatsResponse          = 29,
        DataConsumer_SetSubchannelsResponse    = 30,
        DataConsumer_AddSubchannelResponse     = 31,
        DataConsumer_RemoveSubchannelResponse  = 32,
    }

    public class BodyUnion
    {
        public Body Type { get; set; }
        public object Value { get; set; }

        public BodyUnion()
        {
            this.Type = Body.NONE;
            this.Value = null;
        }

        public T As<T>() where T : class { return this.Value as T; }
        public DumpResponseT AsWorker_DumpResponse() { return this.As<DumpResponseT>(); }
        public static BodyUnion FromWorker_DumpResponse(DumpResponseT _worker_dumpresponse) { return new BodyUnion { Type = Body.Worker_DumpResponse, Value = _worker_dumpresponse }; }
        public ResourceUsageResponseT AsWorker_ResourceUsageResponse() { return this.As<ResourceUsageResponseT>(); }
        public static BodyUnion FromWorker_ResourceUsageResponse(ResourceUsageResponseT _worker_resourceusageresponse) { return new BodyUnion { Type = Body.Worker_ResourceUsageResponse, Value = _worker_resourceusageresponse }; }
        public MediasoupSharp.FlatBuffers.WebRtcServer.T.DumpResponseT AsWebRtcServer_DumpResponse() { return this.As<MediasoupSharp.FlatBuffers.WebRtcServer.T.DumpResponseT>(); }
        public static BodyUnion FromWebRtcServer_DumpResponse(MediasoupSharp.FlatBuffers.WebRtcServer.T.DumpResponseT _webrtcserver_dumpresponse) { return new BodyUnion { Type = Body.WebRtcServer_DumpResponse, Value = _webrtcserver_dumpresponse }; }
        public Router.DumpResponseT AsRouter_DumpResponse() { return this.As<Router.DumpResponseT>(); }
        public static BodyUnion FromRouter_DumpResponse(Router.DumpResponseT _router_dumpresponse) { return new BodyUnion { Type = Body.Router_DumpResponse, Value = _router_dumpresponse }; }
        public ProduceResponseT AsTransport_ProduceResponse() { return this.As<ProduceResponseT>(); }
        public static BodyUnion FromTransport_ProduceResponse(ProduceResponseT _transport_produceresponse) { return new BodyUnion { Type = Body.Transport_ProduceResponse, Value = _transport_produceresponse }; }
        public ConsumeResponseT AsTransport_ConsumeResponse() { return this.As<ConsumeResponseT>(); }
        public static BodyUnion FromTransport_ConsumeResponse(ConsumeResponseT _transport_consumeresponse) { return new BodyUnion { Type = Body.Transport_ConsumeResponse, Value = _transport_consumeresponse }; }
        public RestartIceResponseT AsTransport_RestartIceResponse() { return this.As<RestartIceResponseT>(); }
        public static BodyUnion FromTransport_RestartIceResponse(RestartIceResponseT _transport_restarticeresponse) { return new BodyUnion { Type = Body.Transport_RestartIceResponse, Value = _transport_restarticeresponse }; }
        public ConnectResponseT AsPlainTransport_ConnectResponse() { return this.As<ConnectResponseT>(); }
        public static BodyUnion FromPlainTransport_ConnectResponse(ConnectResponseT _plaintransport_connectresponse) { return new BodyUnion { Type = Body.PlainTransport_ConnectResponse, Value = _plaintransport_connectresponse }; }
        public MediasoupSharp.FlatBuffers.PlainTransport.T.DumpResponseT AsPlainTransport_DumpResponse() { return this.As<MediasoupSharp.FlatBuffers.PlainTransport.T.DumpResponseT>(); }
        public static BodyUnion FromPlainTransport_DumpResponse(MediasoupSharp.FlatBuffers.PlainTransport.T.DumpResponseT _plaintransport_dumpresponse) { return new BodyUnion { Type = Body.PlainTransport_DumpResponse, Value = _plaintransport_dumpresponse }; }
        public GetStatsResponseT AsPlainTransport_GetStatsResponse() { return this.As<GetStatsResponseT>(); }
        public static BodyUnion FromPlainTransport_GetStatsResponse(GetStatsResponseT _plaintransport_getstatsresponse) { return new BodyUnion { Type = Body.PlainTransport_GetStatsResponse, Value = _plaintransport_getstatsresponse }; }
        public MediasoupSharp.FlatBuffers.PipeTransport.T.ConnectResponseT AsPipeTransport_ConnectResponse() { return this.As<MediasoupSharp.FlatBuffers.PipeTransport.T.ConnectResponseT>(); }
        public static BodyUnion FromPipeTransport_ConnectResponse(MediasoupSharp.FlatBuffers.PipeTransport.T.ConnectResponseT _pipetransport_connectresponse) { return new BodyUnion { Type = Body.PipeTransport_ConnectResponse, Value = _pipetransport_connectresponse }; }
        public MediasoupSharp.FlatBuffers.PipeTransport.T.DumpResponseT AsPipeTransport_DumpResponse() { return this.As<MediasoupSharp.FlatBuffers.PipeTransport.T.DumpResponseT>(); }
        public static BodyUnion FromPipeTransport_DumpResponse(MediasoupSharp.FlatBuffers.PipeTransport.T.DumpResponseT _pipetransport_dumpresponse) { return new BodyUnion { Type = Body.PipeTransport_DumpResponse, Value = _pipetransport_dumpresponse }; }
        public MediasoupSharp.FlatBuffers.PipeTransport.T.GetStatsResponseT AsPipeTransport_GetStatsResponse() { return this.As<MediasoupSharp.FlatBuffers.PipeTransport.T.GetStatsResponseT>(); }
        public static BodyUnion FromPipeTransport_GetStatsResponse(MediasoupSharp.FlatBuffers.PipeTransport.T.GetStatsResponseT _pipetransport_getstatsresponse) { return new BodyUnion { Type = Body.PipeTransport_GetStatsResponse, Value = _pipetransport_getstatsresponse }; }
        public MediasoupSharp.FlatBuffers.DirectTransport.T.DumpResponseT AsDirectTransport_DumpResponse() { return this.As<MediasoupSharp.FlatBuffers.DirectTransport.T.DumpResponseT>(); }
        public static BodyUnion FromDirectTransport_DumpResponse(MediasoupSharp.FlatBuffers.DirectTransport.T.DumpResponseT _directtransport_dumpresponse) { return new BodyUnion { Type = Body.DirectTransport_DumpResponse, Value = _directtransport_dumpresponse }; }
        public MediasoupSharp.FlatBuffers.DirectTransport.T.GetStatsResponseT AsDirectTransport_GetStatsResponse() { return this.As<MediasoupSharp.FlatBuffers.DirectTransport.T.GetStatsResponseT>(); }
        public static BodyUnion FromDirectTransport_GetStatsResponse(MediasoupSharp.FlatBuffers.DirectTransport.T.GetStatsResponseT _directtransport_getstatsresponse) { return new BodyUnion { Type = Body.DirectTransport_GetStatsResponse, Value = _directtransport_getstatsresponse }; }
        public MediasoupSharp.FlatBuffers.WebRtcTransport.T.ConnectResponseT AsWebRtcTransport_ConnectResponse() { return this.As<MediasoupSharp.FlatBuffers.WebRtcTransport.T.ConnectResponseT>(); }
        public static BodyUnion FromWebRtcTransport_ConnectResponse(MediasoupSharp.FlatBuffers.WebRtcTransport.T.ConnectResponseT _webrtctransport_connectresponse) { return new BodyUnion { Type = Body.WebRtcTransport_ConnectResponse, Value = _webrtctransport_connectresponse }; }
        public MediasoupSharp.FlatBuffers.WebRtcTransport.T.DumpResponseT AsWebRtcTransport_DumpResponse() { return this.As<MediasoupSharp.FlatBuffers.WebRtcTransport.T.DumpResponseT>(); }
        public static BodyUnion FromWebRtcTransport_DumpResponse(MediasoupSharp.FlatBuffers.WebRtcTransport.T.DumpResponseT _webrtctransport_dumpresponse) { return new BodyUnion { Type = Body.WebRtcTransport_DumpResponse, Value = _webrtctransport_dumpresponse }; }
        public MediasoupSharp.FlatBuffers.WebRtcTransport.T.GetStatsResponseT AsWebRtcTransport_GetStatsResponse() { return this.As<MediasoupSharp.FlatBuffers.WebRtcTransport.T.GetStatsResponseT>(); }
        public static BodyUnion FromWebRtcTransport_GetStatsResponse(MediasoupSharp.FlatBuffers.WebRtcTransport.T.GetStatsResponseT _webrtctransport_getstatsresponse) { return new BodyUnion { Type = Body.WebRtcTransport_GetStatsResponse, Value = _webrtctransport_getstatsresponse }; }
        public MediasoupSharp.FlatBuffers.Producer.T.DumpResponseT AsProducer_DumpResponse() { return this.As<MediasoupSharp.FlatBuffers.Producer.T.DumpResponseT>(); }
        public static BodyUnion FromProducer_DumpResponse(MediasoupSharp.FlatBuffers.Producer.T.DumpResponseT _producer_dumpresponse) { return new BodyUnion { Type = Body.Producer_DumpResponse, Value = _producer_dumpresponse }; }
        public MediasoupSharp.FlatBuffers.Producer.T.GetStatsResponseT AsProducer_GetStatsResponse() { return this.As<MediasoupSharp.FlatBuffers.Producer.T.GetStatsResponseT>(); }
        public static BodyUnion FromProducer_GetStatsResponse(MediasoupSharp.FlatBuffers.Producer.T.GetStatsResponseT _producer_getstatsresponse) { return new BodyUnion { Type = Body.Producer_GetStatsResponse, Value = _producer_getstatsresponse }; }
        public MediasoupSharp.FlatBuffers.Consumer.T.DumpResponseT AsConsumer_DumpResponse() { return this.As<MediasoupSharp.FlatBuffers.Consumer.T.DumpResponseT>(); }
        public static BodyUnion FromConsumer_DumpResponse(MediasoupSharp.FlatBuffers.Consumer.T.DumpResponseT _consumer_dumpresponse) { return new BodyUnion { Type = Body.Consumer_DumpResponse, Value = _consumer_dumpresponse }; }
        public MediasoupSharp.FlatBuffers.Consumer.T.GetStatsResponseT AsConsumer_GetStatsResponse() { return this.As<MediasoupSharp.FlatBuffers.Consumer.T.GetStatsResponseT>(); }
        public static BodyUnion FromConsumer_GetStatsResponse(MediasoupSharp.FlatBuffers.Consumer.T.GetStatsResponseT _consumer_getstatsresponse) { return new BodyUnion { Type = Body.Consumer_GetStatsResponse, Value = _consumer_getstatsresponse }; }
        public SetPreferredLayersResponseT AsConsumer_SetPreferredLayersResponse() { return this.As<SetPreferredLayersResponseT>(); }
        public static BodyUnion FromConsumer_SetPreferredLayersResponse(SetPreferredLayersResponseT _consumer_setpreferredlayersresponse) { return new BodyUnion { Type = Body.Consumer_SetPreferredLayersResponse, Value = _consumer_setpreferredlayersresponse }; }
        public SetPriorityResponseT AsConsumer_SetPriorityResponse() { return this.As<SetPriorityResponseT>(); }
        public static BodyUnion FromConsumer_SetPriorityResponse(SetPriorityResponseT _consumer_setpriorityresponse) { return new BodyUnion { Type = Body.Consumer_SetPriorityResponse, Value = _consumer_setpriorityresponse }; }
        public MediasoupSharp.FlatBuffers.DataProducer.T.DumpResponseT AsDataProducer_DumpResponse() { return this.As<MediasoupSharp.FlatBuffers.DataProducer.T.DumpResponseT>(); }
        public static BodyUnion FromDataProducer_DumpResponse(MediasoupSharp.FlatBuffers.DataProducer.T.DumpResponseT _dataproducer_dumpresponse) { return new BodyUnion { Type = Body.DataProducer_DumpResponse, Value = _dataproducer_dumpresponse }; }
        public MediasoupSharp.FlatBuffers.DataProducer.T.GetStatsResponseT AsDataProducer_GetStatsResponse() { return this.As<MediasoupSharp.FlatBuffers.DataProducer.T.GetStatsResponseT>(); }
        public static BodyUnion FromDataProducer_GetStatsResponse(MediasoupSharp.FlatBuffers.DataProducer.T.GetStatsResponseT _dataproducer_getstatsresponse) { return new BodyUnion { Type = Body.DataProducer_GetStatsResponse, Value = _dataproducer_getstatsresponse }; }
        public GetBufferedAmountResponseT AsDataConsumer_GetBufferedAmountResponse() { return this.As<GetBufferedAmountResponseT>(); }
        public static BodyUnion FromDataConsumer_GetBufferedAmountResponse(GetBufferedAmountResponseT _dataconsumer_getbufferedamountresponse) { return new BodyUnion { Type = Body.DataConsumer_GetBufferedAmountResponse, Value = _dataconsumer_getbufferedamountresponse }; }
        public MediasoupSharp.FlatBuffers.DataConsumer.T.DumpResponseT AsDataConsumer_DumpResponse() { return this.As<MediasoupSharp.FlatBuffers.DataConsumer.T.DumpResponseT>(); }
        public static BodyUnion FromDataConsumer_DumpResponse(MediasoupSharp.FlatBuffers.DataConsumer.T.DumpResponseT _dataconsumer_dumpresponse) { return new BodyUnion { Type = Body.DataConsumer_DumpResponse, Value = _dataconsumer_dumpresponse }; }
        public MediasoupSharp.FlatBuffers.DataConsumer.T.GetStatsResponseT AsDataConsumer_GetStatsResponse() { return this.As<MediasoupSharp.FlatBuffers.DataConsumer.T.GetStatsResponseT>(); }
        public static BodyUnion FromDataConsumer_GetStatsResponse(MediasoupSharp.FlatBuffers.DataConsumer.T.GetStatsResponseT _dataconsumer_getstatsresponse) { return new BodyUnion { Type = Body.DataConsumer_GetStatsResponse, Value = _dataconsumer_getstatsresponse }; }
        public SetSubchannelsResponseT AsDataConsumer_SetSubchannelsResponse() { return this.As<SetSubchannelsResponseT>(); }
        public static BodyUnion FromDataConsumer_SetSubchannelsResponse(SetSubchannelsResponseT _dataconsumer_setsubchannelsresponse) { return new BodyUnion { Type = Body.DataConsumer_SetSubchannelsResponse, Value = _dataconsumer_setsubchannelsresponse }; }
        public AddSubchannelResponseT AsDataConsumer_AddSubchannelResponse() { return this.As<AddSubchannelResponseT>(); }
        public static BodyUnion FromDataConsumer_AddSubchannelResponse(AddSubchannelResponseT _dataconsumer_addsubchannelresponse) { return new BodyUnion { Type = Body.DataConsumer_AddSubchannelResponse, Value = _dataconsumer_addsubchannelresponse }; }
        public RemoveSubchannelResponseT AsDataConsumer_RemoveSubchannelResponse() { return this.As<RemoveSubchannelResponseT>(); }
        public static BodyUnion FromDataConsumer_RemoveSubchannelResponse(RemoveSubchannelResponseT _dataconsumer_removesubchannelresponse) { return new BodyUnion { Type = Body.DataConsumer_RemoveSubchannelResponse, Value = _dataconsumer_removesubchannelresponse }; }

        public static int Pack(Google.FlatBuffers.FlatBufferBuilder builder, BodyUnion _o)
        {
            switch(_o.Type)
            {
                default:
                    return 0;
                case Body.Worker_DumpResponse:
                    return DumpResponse.Pack(builder, _o.AsWorker_DumpResponse()).Value;
                case Body.Worker_ResourceUsageResponse:
                    return ResourceUsageResponse.Pack(builder, _o.AsWorker_ResourceUsageResponse()).Value;
                case Body.WebRtcServer_DumpResponse:
                    return WebRtcServer.DumpResponse.Pack(builder, _o.AsWebRtcServer_DumpResponse()).Value;
                case Body.Router_DumpResponse:
                    return Router.DumpResponse.Pack(builder, _o.AsRouter_DumpResponse()).Value;
                case Body.Transport_ProduceResponse:
                    return ProduceResponse.Pack(builder, _o.AsTransport_ProduceResponse()).Value;
                case Body.Transport_ConsumeResponse:
                    return ConsumeResponse.Pack(builder, _o.AsTransport_ConsumeResponse()).Value;
                case Body.Transport_RestartIceResponse:
                    return RestartIceResponse.Pack(builder, _o.AsTransport_RestartIceResponse()).Value;
                case Body.PlainTransport_ConnectResponse:
                    return ConnectResponse.Pack(builder, _o.AsPlainTransport_ConnectResponse()).Value;
                case Body.PlainTransport_DumpResponse:
                    return PlainTransport.DumpResponse.Pack(builder, _o.AsPlainTransport_DumpResponse()).Value;
                case Body.PlainTransport_GetStatsResponse:
                    return GetStatsResponse.Pack(builder, _o.AsPlainTransport_GetStatsResponse()).Value;
                case Body.PipeTransport_ConnectResponse:
                    return PipeTransport.ConnectResponse.Pack(builder, _o.AsPipeTransport_ConnectResponse()).Value;
                case Body.PipeTransport_DumpResponse:
                    return PipeTransport.DumpResponse.Pack(builder, _o.AsPipeTransport_DumpResponse()).Value;
                case Body.PipeTransport_GetStatsResponse:
                    return PipeTransport.GetStatsResponse.Pack(builder, _o.AsPipeTransport_GetStatsResponse()).Value;
                case Body.DirectTransport_DumpResponse:
                    return DirectTransport.DumpResponse.Pack(builder, _o.AsDirectTransport_DumpResponse()).Value;
                case Body.DirectTransport_GetStatsResponse:
                    return DirectTransport.GetStatsResponse.Pack(builder, _o.AsDirectTransport_GetStatsResponse()).Value;
                case Body.WebRtcTransport_ConnectResponse:
                    return WebRtcTransport.ConnectResponse.Pack(builder, _o.AsWebRtcTransport_ConnectResponse()).Value;
                case Body.WebRtcTransport_DumpResponse:
                    return WebRtcTransport.DumpResponse.Pack(builder, _o.AsWebRtcTransport_DumpResponse()).Value;
                case Body.WebRtcTransport_GetStatsResponse:
                    return WebRtcTransport.GetStatsResponse.Pack(builder, _o.AsWebRtcTransport_GetStatsResponse()).Value;
                case Body.Producer_DumpResponse:
                    return Producer.DumpResponse.Pack(builder, _o.AsProducer_DumpResponse()).Value;
                case Body.Producer_GetStatsResponse:
                    return Producer.GetStatsResponse.Pack(builder, _o.AsProducer_GetStatsResponse()).Value;
                case Body.Consumer_DumpResponse:
                    return Consumer.DumpResponse.Pack(builder, _o.AsConsumer_DumpResponse()).Value;
                case Body.Consumer_GetStatsResponse:
                    return Consumer.GetStatsResponse.Pack(builder, _o.AsConsumer_GetStatsResponse()).Value;
                case Body.Consumer_SetPreferredLayersResponse:
                    return SetPreferredLayersResponse.Pack(builder, _o.AsConsumer_SetPreferredLayersResponse()).Value;
                case Body.Consumer_SetPriorityResponse:
                    return SetPriorityResponse.Pack(builder, _o.AsConsumer_SetPriorityResponse()).Value;
                case Body.DataProducer_DumpResponse:
                    return DataProducer.DumpResponse.Pack(builder, _o.AsDataProducer_DumpResponse()).Value;
                case Body.DataProducer_GetStatsResponse:
                    return DataProducer.GetStatsResponse.Pack(builder, _o.AsDataProducer_GetStatsResponse()).Value;
                case Body.DataConsumer_GetBufferedAmountResponse:
                    return GetBufferedAmountResponse.Pack(builder, _o.AsDataConsumer_GetBufferedAmountResponse()).Value;
                case Body.DataConsumer_DumpResponse:
                    return DataConsumer.DumpResponse.Pack(builder, _o.AsDataConsumer_DumpResponse()).Value;
                case Body.DataConsumer_GetStatsResponse:
                    return DataConsumer.GetStatsResponse.Pack(builder, _o.AsDataConsumer_GetStatsResponse()).Value;
                case Body.DataConsumer_SetSubchannelsResponse:
                    return SetSubchannelsResponse.Pack(builder, _o.AsDataConsumer_SetSubchannelsResponse()).Value;
                case Body.DataConsumer_AddSubchannelResponse:
                    return AddSubchannelResponse.Pack(builder, _o.AsDataConsumer_AddSubchannelResponse()).Value;
                case Body.DataConsumer_RemoveSubchannelResponse:
                    return RemoveSubchannelResponse.Pack(builder, _o.AsDataConsumer_RemoveSubchannelResponse()).Value;
            }
        }
    }
}
