// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System.Text.Json.Serialization;
using Google.FlatBuffers;
using MediasoupSharp.FlatBuffers.Consumer.T;

namespace FlatBuffers.Consumer
{
    public struct SetPreferredLayersResponse : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static SetPreferredLayersResponse GetRootAsSetPreferredLayersResponse(ByteBuffer _bb) { return GetRootAsSetPreferredLayersResponse(_bb, new SetPreferredLayersResponse()); }
        public static SetPreferredLayersResponse GetRootAsSetPreferredLayersResponse(ByteBuffer _bb, SetPreferredLayersResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public SetPreferredLayersResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public ConsumerLayers? PreferredLayers { get { int o = __p.__offset(4); return o != 0 ? (ConsumerLayers?)(new ConsumerLayers()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<SetPreferredLayersResponse> CreateSetPreferredLayersResponse(FlatBufferBuilder builder,
                                                                                          Offset<ConsumerLayers> preferred_layersOffset = default(Offset<ConsumerLayers>))
        {
            builder.StartTable(1);
            SetPreferredLayersResponse.AddPreferredLayers(builder, preferred_layersOffset);
            return SetPreferredLayersResponse.EndSetPreferredLayersResponse(builder);
        }

        public static void StartSetPreferredLayersResponse(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddPreferredLayers(FlatBufferBuilder builder, Offset<ConsumerLayers> preferredLayersOffset) { builder.AddOffset(0, preferredLayersOffset.Value, 0); }
        public static Offset<SetPreferredLayersResponse> EndSetPreferredLayersResponse(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            return new Offset<SetPreferredLayersResponse>(o);
        }
        public SetPreferredLayersResponseT UnPack()
        {
            var _o = new SetPreferredLayersResponseT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(SetPreferredLayersResponseT _o)
        {
            _o.PreferredLayers = this.PreferredLayers.HasValue ? this.PreferredLayers.Value.UnPack() : null;
        }
        public static Offset<SetPreferredLayersResponse> Pack(FlatBufferBuilder builder, SetPreferredLayersResponseT _o)
        {
            if(_o == null)
                return default(Offset<SetPreferredLayersResponse>);
            var _preferred_layers = _o.PreferredLayers == null ? default(Offset<ConsumerLayers>) : ConsumerLayers.Pack(builder, _o.PreferredLayers);
            return CreateSetPreferredLayersResponse(
              builder,
              _preferred_layers);
        }
    }
}
