namespace MediasoupSharp.Worker;

public record WorkerSettings<TWorkerAppData>
{
    ///
    /// Logging level for logs generated by the media worker subprocesses (check
    /// the Debugging documentation). Valid values are 'debug', 'warn', 'error' and
    /// 'none'. Default 'error'.
    ///
    public WorkerLogLevel? LogLevel { get; set; }

    ///
    /// Log tags for debugging. Check the meaning of each available tag in the
    /// Debugging documentation.
    ////
    public List<WorkerLogTag>? LogTags { get; set; }

    ///
    /// Minimun RTC port for ICE, DTLS, RTP, etc. Default 10000.
    ///
    public int? RtcMinPort { get; set; }

    ///
    /// Maximum RTC port for ICE, DTLS, RTP, etc. Default 59999.
    ////
    public int? RtcMaxPort { get; set; }

    ///
    /// Path to the DTLS public certificate file in PEM format. If unset, a
    /// certificate is dynamically created.
    ///
    public string? DtlsCertificateFile { get; set; }

    ///
    /// Path to the DTLS certificate private key file in PEM format. If unset, a
    /// certificate is dynamically created.
    ///
    public string? DtlsPrivateKeyFile { get; set; }

    ///
    /// Field trials for libwebrtc.
    /// @private
    ///
    /// NOTE: For advanced users only. An invalid value will make the worker crash.
    /// Default value is
    /// "WebRTC-Bwe-AlrLimitedBackoff/Enabled/".
    ///
    public string? LibwebrtcFieldTrials { get; set; }

    ///
    /// Custom application data.
    ///
    public TWorkerAppData? AppData { get; set; }
}