// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using System.Collections.Generic;
using Google.FlatBuffers;
using System.Text.Json.Serialization;
using MediasoupSharp.FlatBuffers.Transport.T;

namespace FlatBuffers.WebRtcTransport
{
    public class ListenIndividualT
    {
        public List<ListenInfoT> ListenInfos { get; set; }
    }
}
