<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../Build.props" />
    
    <PropertyGroup>
        <MediasoupVersion>3.15.7</MediasoupVersion>
        <TargetFrameworks>net7.0;</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <Version>$(MediasoupVersion)</Version>
        <PackageReleaseNotes>mediasoup-sharp $(MediasoupVersion)</PackageReleaseNotes>
        <AssemblyVersion>$(MediasoupVersion)</AssemblyVersion>
        <FileVersion>$(MediasoupVersion)</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Antelcat.AutoGen" Version="3.0.0-preview-250220-1" />
        <PackageReference Include="Antelcat.FlatBuffers" Version="25.2.10" />
        <PackageReference Include="Antelcat.LibuvSharp" Version="1.0.1" />
        <PackageReference Include="Antelcat.NodeSharp" Version="0.4.1" />
        <PackageReference Include="Google.FlatBuffers" Version="25.2.10" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.0" />
        <PackageReference Include="Microsoft.VisualStudio.Threading" Version="17.11.20" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Antelcat.MediasoupSharp.Test" />
        <InternalsVisibleTo Include="Antelcat.MediasoupSharp.AspNetCore" />
        <InternalsVisibleTo Include="Antelcat.MediasoupSharp.Demo" />
        <AdditionalFiles LinkBase="fbs" Include="..\..\mediasoup\worker\fbs\*.fbs" />
    </ItemGroup>

</Project>
