// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using FlatBuffers.Transport;
using MediasoupSharp.FlatBuffers.PlainTransport.T;
using Tuple = FlatBuffers.Transport.Tuple;

namespace FlatBuffers.PlainTransport
{
    using Google.FlatBuffers;
    using System.Text.Json.Serialization;

    public struct GetStatsResponse : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static GetStatsResponse GetRootAsGetStatsResponse(ByteBuffer _bb) { return GetRootAsGetStatsResponse(_bb, new GetStatsResponse()); }
        public static GetStatsResponse GetRootAsGetStatsResponse(ByteBuffer _bb, GetStatsResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public GetStatsResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public Stats? Base { get { int o = __p.__offset(4); return o != 0 ? (Stats?)(new Stats()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public bool RtcpMux { get { int o = __p.__offset(6); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public bool Comedia { get { int o = __p.__offset(8); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public Tuple? Tuple { get { int o = __p.__offset(10); return o != 0 ? (Tuple?)(new Tuple()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public Tuple? RtcpTuple { get { int o = __p.__offset(12); return o != 0 ? (Tuple?)(new Tuple()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<GetStatsResponse> CreateGetStatsResponse(FlatBufferBuilder builder,
                                                                      Offset<Stats> @baseOffset = default(Offset<Stats>),
                                                                      bool rtcp_mux = false,
                                                                      bool comedia = false,
                                                                      Offset<Tuple> tupleOffset = default(Offset<Tuple>),
                                                                      Offset<Tuple> rtcp_tupleOffset = default(Offset<Tuple>))
        {
            builder.StartTable(5);
            GetStatsResponse.AddRtcpTuple(builder, rtcp_tupleOffset);
            GetStatsResponse.AddTuple(builder, tupleOffset);
            GetStatsResponse.AddBase(builder, @baseOffset);
            GetStatsResponse.AddComedia(builder, comedia);
            GetStatsResponse.AddRtcpMux(builder, rtcp_mux);
            return GetStatsResponse.EndGetStatsResponse(builder);
        }

        public static void StartGetStatsResponse(FlatBufferBuilder builder) { builder.StartTable(5); }
        public static void AddBase(FlatBufferBuilder builder, Offset<Stats> baseOffset) { builder.AddOffset(0, baseOffset.Value, 0); }
        public static void AddRtcpMux(FlatBufferBuilder builder, bool rtcpMux) { builder.AddBool(1, rtcpMux, false); }
        public static void AddComedia(FlatBufferBuilder builder, bool comedia) { builder.AddBool(2, comedia, false); }
        public static void AddTuple(FlatBufferBuilder builder, Offset<Tuple> tupleOffset) { builder.AddOffset(3, tupleOffset.Value, 0); }
        public static void AddRtcpTuple(FlatBufferBuilder builder, Offset<Tuple> rtcpTupleOffset) { builder.AddOffset(4, rtcpTupleOffset.Value, 0); }
        public static Offset<GetStatsResponse> EndGetStatsResponse(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // base
            builder.Required(o, 10);  // tuple
            return new Offset<GetStatsResponse>(o);
        }
        public GetStatsResponseT UnPack()
        {
            var _o = new GetStatsResponseT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(GetStatsResponseT _o)
        {
            _o.Base = this.Base.HasValue ? this.Base.Value.UnPack() : null;
            _o.RtcpMux = this.RtcpMux;
            _o.Comedia = this.Comedia;
            _o.Tuple = this.Tuple.HasValue ? this.Tuple.Value.UnPack() : null;
            _o.RtcpTuple = this.RtcpTuple.HasValue ? this.RtcpTuple.Value.UnPack() : null;
        }
        public static Offset<GetStatsResponse> Pack(FlatBufferBuilder builder, GetStatsResponseT _o)
        {
            if(_o == null)
                return default(Offset<GetStatsResponse>);
            var _base = _o.Base == null ? default(Offset<Stats>) : Stats.Pack(builder, _o.Base);
            var _tuple = _o.Tuple == null ? default(Offset<Tuple>) : Transport.Tuple.Pack(builder, _o.Tuple);
            var _rtcp_tuple = _o.RtcpTuple == null ? default(Offset<Tuple>) : Transport.Tuple.Pack(builder, _o.RtcpTuple);
            return CreateGetStatsResponse(
              builder,
              _base,
              _o.RtcpMux,
              _o.Comedia,
              _tuple,
              _rtcp_tuple);
        }
    }
}
