// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using FlatBuffers.Transport;
using MediasoupSharp.FlatBuffers.PlainTransport.T;
using Tuple = FlatBuffers.Transport.Tuple;

namespace FlatBuffers.PlainTransport
{
    using Google.FlatBuffers;
    using System.Text.Json.Serialization;

    public struct TupleNotification : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static TupleNotification GetRootAsTupleNotification(ByteBuffer _bb) { return GetRootAsTupleNotification(_bb, new TupleNotification()); }
        public static TupleNotification GetRootAsTupleNotification(ByteBuffer _bb, TupleNotification obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public TupleNotification __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public Tuple? Tuple { get { int o = __p.__offset(4); return o != 0 ? (Tuple?)(new Tuple()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<TupleNotification> CreateTupleNotification(FlatBufferBuilder builder,
                                                                        Offset<Tuple> tupleOffset = default(Offset<Tuple>))
        {
            builder.StartTable(1);
            TupleNotification.AddTuple(builder, tupleOffset);
            return TupleNotification.EndTupleNotification(builder);
        }

        public static void StartTupleNotification(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddTuple(FlatBufferBuilder builder, Offset<Tuple> tupleOffset) { builder.AddOffset(0, tupleOffset.Value, 0); }
        public static Offset<TupleNotification> EndTupleNotification(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // tuple
            return new Offset<TupleNotification>(o);
        }
        public TupleNotificationT UnPack()
        {
            var _o = new TupleNotificationT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(TupleNotificationT _o)
        {
            _o.Tuple = this.Tuple.HasValue ? this.Tuple.Value.UnPack() : null;
        }
        public static Offset<TupleNotification> Pack(FlatBufferBuilder builder, TupleNotificationT _o)
        {
            if(_o == null)
                return default(Offset<TupleNotification>);
            var _tuple = _o.Tuple == null ? default(Offset<Tuple>) : Transport.Tuple.Pack(builder, _o.Tuple);
            return CreateTupleNotification(
              builder,
              _tuple);
        }
    }
}
