// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Google.FlatBuffers;

namespace FlatBuffers.AudioLevelObserver
{
    public class VolumesNotificationT
    {
        public List<VolumeT> Volumes { get; set; }
    }
}
