// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using Google.FlatBuffers;
using System.Text.Json.Serialization;
using FlatBuffers.Transport;
using MediasoupSharp.FlatBuffers.DirectTransport.T;
using Options = FlatBuffers.Transport.Options;

namespace FlatBuffers.DirectTransport
{
    public struct DirectTransportOptions : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
        public static DirectTransportOptions GetRootAsDirectTransportOptions(ByteBuffer _bb) { return GetRootAsDirectTransportOptions(_bb, new DirectTransportOptions()); }
        public static DirectTransportOptions GetRootAsDirectTransportOptions(ByteBuffer _bb, DirectTransportOptions obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
        public DirectTransportOptions __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public Options? Base { get { int o = __p.__offset(4); return o != 0 ? (Options?)(new Options()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<DirectTransportOptions> CreateDirectTransportOptions(FlatBufferBuilder builder,
                                                                                  Offset<Options> @baseOffset = default(Offset<Options>))
        {
            builder.StartTable(1);
            DirectTransportOptions.AddBase(builder, @baseOffset);
            return DirectTransportOptions.EndDirectTransportOptions(builder);
        }

        public static void StartDirectTransportOptions(FlatBufferBuilder builder) { builder.StartTable(1); }
        public static void AddBase(FlatBufferBuilder builder, Offset<Options> baseOffset) { builder.AddOffset(0, baseOffset.Value, 0); }
        public static Offset<DirectTransportOptions> EndDirectTransportOptions(FlatBufferBuilder builder)
        {
            int o = builder.EndTable();
            builder.Required(o, 4);  // base
            return new Offset<DirectTransportOptions>(o);
        }
        public DirectTransportOptionsT UnPack()
        {
            var _o = new DirectTransportOptionsT();
            this.UnPackTo(_o);
            return _o;
        }
        public void UnPackTo(DirectTransportOptionsT _o)
        {
            _o.Base = this.Base.HasValue ? this.Base.Value.UnPack() : null;
        }
        public static Offset<DirectTransportOptions> Pack(FlatBufferBuilder builder, DirectTransportOptionsT _o)
        {
            if(_o == null)
                return default(Offset<DirectTransportOptions>);
            var _base = _o.Base == null ? default(Offset<Options>) : Options.Pack(builder, _o.Base);
            return CreateDirectTransportOptions(
              builder,
              _base);
        }
    }
}
